// Code generated by ent, DO NOT EDIT.

package userreferral

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the userreferral type in the database.
	Label = "user_referral"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldInviterID holds the string denoting the inviter_id field in the database.
	FieldInviterID = "inviter_id"
	// FieldInviteeID holds the string denoting the invitee_id field in the database.
	FieldInviteeID = "invitee_id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldInviterRewarded holds the string denoting the inviter_rewarded field in the database.
	FieldInviterRewarded = "inviter_rewarded"
	// FieldInviteeRewarded holds the string denoting the invitee_rewarded field in the database.
	FieldInviteeRewarded = "invitee_rewarded"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeInviter holds the string denoting the inviter edge name in mutations.
	EdgeInviter = "inviter"
	// EdgeInvitee holds the string denoting the invitee edge name in mutations.
	EdgeInvitee = "invitee"
	// Table holds the table name of the userreferral in the database.
	Table = "user_referrals"
	// InviterTable is the table that holds the inviter relation/edge.
	InviterTable = "user_referrals"
	// InviterInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	InviterInverseTable = "users"
	// InviterColumn is the table column denoting the inviter relation/edge.
	InviterColumn = "inviter_id"
	// InviteeTable is the table that holds the invitee relation/edge.
	InviteeTable = "user_referrals"
	// InviteeInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	InviteeInverseTable = "users"
	// InviteeColumn is the table column denoting the invitee relation/edge.
	InviteeColumn = "invitee_id"
)

// Columns holds all SQL columns for userreferral fields.
var Columns = []string{
	FieldID,
	FieldInviterID,
	FieldInviteeID,
	FieldCode,
	FieldInviterRewarded,
	FieldInviteeRewarded,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// DefaultInviterRewarded holds the default value on creation for the "inviter_rewarded" field.
	DefaultInviterRewarded float64
	// DefaultInviteeRewarded holds the default value on creation for the "invitee_rewarded" field.
	DefaultInviteeRewarded float64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the UserReferral queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByInviterID orders the results by the inviter_id field.
func ByInviterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviterID, opts...).ToFunc()
}

// ByInviteeID orders the results by the invitee_id field.
func ByInviteeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteeID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByInviterRewarded orders the results by the inviter_rewarded field.
func ByInviterRewarded(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviterRewarded, opts...).ToFunc()
}

// ByInviteeRewarded orders the results by the invitee_rewarded field.
func ByInviteeRewarded(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteeRewarded, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByInviterField orders the results by inviter field.
func ByInviterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInviterStep(), sql.OrderByField(field, opts...))
	}
}

// ByInviteeField orders the results by invitee field.
func ByInviteeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInviteeStep(), sql.OrderByField(field, opts...))
	}
}
func newInviterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InviterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InviterTable, InviterColumn),
	)
}
func newInviteeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InviteeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, InviteeTable, InviteeColumn),
	)
}
