// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imagecreationasset"
	"github.com/Wei-Shaw/sub2api/ent/imagecreationtemplate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ImageCreationAssetCreate is the builder for creating a ImageCreationAsset entity.
type ImageCreationAssetCreate struct {
	config
	mutation *ImageCreationAssetMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetContent sets the "content" field.
func (_c *ImageCreationAssetCreate) SetContent(v []byte) *ImageCreationAssetCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetContentType sets the "content_type" field.
func (_c *ImageCreationAssetCreate) SetContentType(v string) *ImageCreationAssetCreate {
	_c.mutation.SetContentType(v)
	return _c
}

// SetByteSize sets the "byte_size" field.
func (_c *ImageCreationAssetCreate) SetByteSize(v int) *ImageCreationAssetCreate {
	_c.mutation.SetByteSize(v)
	return _c
}

// SetWidth sets the "width" field.
func (_c *ImageCreationAssetCreate) SetWidth(v int) *ImageCreationAssetCreate {
	_c.mutation.SetWidth(v)
	return _c
}

// SetHeight sets the "height" field.
func (_c *ImageCreationAssetCreate) SetHeight(v int) *ImageCreationAssetCreate {
	_c.mutation.SetHeight(v)
	return _c
}

// SetSourceType sets the "source_type" field.
func (_c *ImageCreationAssetCreate) SetSourceType(v string) *ImageCreationAssetCreate {
	_c.mutation.SetSourceType(v)
	return _c
}

// SetSourceProvider sets the "source_provider" field.
func (_c *ImageCreationAssetCreate) SetSourceProvider(v string) *ImageCreationAssetCreate {
	_c.mutation.SetSourceProvider(v)
	return _c
}

// SetNillableSourceProvider sets the "source_provider" field if the given value is not nil.
func (_c *ImageCreationAssetCreate) SetNillableSourceProvider(v *string) *ImageCreationAssetCreate {
	if v != nil {
		_c.SetSourceProvider(*v)
	}
	return _c
}

// SetSourceModel sets the "source_model" field.
func (_c *ImageCreationAssetCreate) SetSourceModel(v string) *ImageCreationAssetCreate {
	_c.mutation.SetSourceModel(v)
	return _c
}

// SetNillableSourceModel sets the "source_model" field if the given value is not nil.
func (_c *ImageCreationAssetCreate) SetNillableSourceModel(v *string) *ImageCreationAssetCreate {
	if v != nil {
		_c.SetSourceModel(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ImageCreationAssetCreate) SetCreatedBy(v int64) *ImageCreationAssetCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ImageCreationAssetCreate) SetCreatedAt(v time.Time) *ImageCreationAssetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ImageCreationAssetCreate) SetNillableCreatedAt(v *time.Time) *ImageCreationAssetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ImageCreationAssetCreate) SetID(v string) *ImageCreationAssetCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *ImageCreationAssetCreate) SetCreatorID(id int64) *ImageCreationAssetCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *ImageCreationAssetCreate) SetCreator(v *User) *ImageCreationAssetCreate {
	return _c.SetCreatorID(v.ID)
}

// AddDraftTemplateIDs adds the "draft_templates" edge to the ImageCreationTemplate entity by IDs.
func (_c *ImageCreationAssetCreate) AddDraftTemplateIDs(ids ...int64) *ImageCreationAssetCreate {
	_c.mutation.AddDraftTemplateIDs(ids...)
	return _c
}

// AddDraftTemplates adds the "draft_templates" edges to the ImageCreationTemplate entity.
func (_c *ImageCreationAssetCreate) AddDraftTemplates(v ...*ImageCreationTemplate) *ImageCreationAssetCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDraftTemplateIDs(ids...)
}

// AddPublishedTemplateIDs adds the "published_templates" edge to the ImageCreationTemplate entity by IDs.
func (_c *ImageCreationAssetCreate) AddPublishedTemplateIDs(ids ...int64) *ImageCreationAssetCreate {
	_c.mutation.AddPublishedTemplateIDs(ids...)
	return _c
}

// AddPublishedTemplates adds the "published_templates" edges to the ImageCreationTemplate entity.
func (_c *ImageCreationAssetCreate) AddPublishedTemplates(v ...*ImageCreationTemplate) *ImageCreationAssetCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPublishedTemplateIDs(ids...)
}

// Mutation returns the ImageCreationAssetMutation object of the builder.
func (_c *ImageCreationAssetCreate) Mutation() *ImageCreationAssetMutation {
	return _c.mutation
}

// Save creates the ImageCreationAsset in the database.
func (_c *ImageCreationAssetCreate) Save(ctx context.Context) (*ImageCreationAsset, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImageCreationAssetCreate) SaveX(ctx context.Context) *ImageCreationAsset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageCreationAssetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageCreationAssetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ImageCreationAssetCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := imagecreationasset.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImageCreationAssetCreate) check() error {
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "ImageCreationAsset.content"`)}
	}
	if _, ok := _c.mutation.ContentType(); !ok {
		return &ValidationError{Name: "content_type", err: errors.New(`ent: missing required field "ImageCreationAsset.content_type"`)}
	}
	if v, ok := _c.mutation.ContentType(); ok {
		if err := imagecreationasset.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.content_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ByteSize(); !ok {
		return &ValidationError{Name: "byte_size", err: errors.New(`ent: missing required field "ImageCreationAsset.byte_size"`)}
	}
	if v, ok := _c.mutation.ByteSize(); ok {
		if err := imagecreationasset.ByteSizeValidator(v); err != nil {
			return &ValidationError{Name: "byte_size", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.byte_size": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Width(); !ok {
		return &ValidationError{Name: "width", err: errors.New(`ent: missing required field "ImageCreationAsset.width"`)}
	}
	if v, ok := _c.mutation.Width(); ok {
		if err := imagecreationasset.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.width": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Height(); !ok {
		return &ValidationError{Name: "height", err: errors.New(`ent: missing required field "ImageCreationAsset.height"`)}
	}
	if v, ok := _c.mutation.Height(); ok {
		if err := imagecreationasset.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.height": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SourceType(); !ok {
		return &ValidationError{Name: "source_type", err: errors.New(`ent: missing required field "ImageCreationAsset.source_type"`)}
	}
	if v, ok := _c.mutation.SourceType(); ok {
		if err := imagecreationasset.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.source_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SourceProvider(); ok {
		if err := imagecreationasset.SourceProviderValidator(v); err != nil {
			return &ValidationError{Name: "source_provider", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.source_provider": %w`, err)}
		}
	}
	if v, ok := _c.mutation.SourceModel(); ok {
		if err := imagecreationasset.SourceModelValidator(v); err != nil {
			return &ValidationError{Name: "source_model", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.source_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "ImageCreationAsset.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ImageCreationAsset.created_at"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := imagecreationasset.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.id": %w`, err)}
		}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required edge "ImageCreationAsset.creator"`)}
	}
	return nil
}

func (_c *ImageCreationAssetCreate) sqlSave(ctx context.Context) (*ImageCreationAsset, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ImageCreationAsset.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImageCreationAssetCreate) createSpec() (*ImageCreationAsset, *sqlgraph.CreateSpec) {
	var (
		_node = &ImageCreationAsset{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(imagecreationasset.Table, sqlgraph.NewFieldSpec(imagecreationasset.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(imagecreationasset.FieldContent, field.TypeBytes, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.ContentType(); ok {
		_spec.SetField(imagecreationasset.FieldContentType, field.TypeString, value)
		_node.ContentType = value
	}
	if value, ok := _c.mutation.ByteSize(); ok {
		_spec.SetField(imagecreationasset.FieldByteSize, field.TypeInt, value)
		_node.ByteSize = value
	}
	if value, ok := _c.mutation.Width(); ok {
		_spec.SetField(imagecreationasset.FieldWidth, field.TypeInt, value)
		_node.Width = value
	}
	if value, ok := _c.mutation.Height(); ok {
		_spec.SetField(imagecreationasset.FieldHeight, field.TypeInt, value)
		_node.Height = value
	}
	if value, ok := _c.mutation.SourceType(); ok {
		_spec.SetField(imagecreationasset.FieldSourceType, field.TypeString, value)
		_node.SourceType = value
	}
	if value, ok := _c.mutation.SourceProvider(); ok {
		_spec.SetField(imagecreationasset.FieldSourceProvider, field.TypeString, value)
		_node.SourceProvider = &value
	}
	if value, ok := _c.mutation.SourceModel(); ok {
		_spec.SetField(imagecreationasset.FieldSourceModel, field.TypeString, value)
		_node.SourceModel = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(imagecreationasset.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationasset.CreatorTable,
			Columns: []string{imagecreationasset.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DraftTemplatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imagecreationasset.DraftTemplatesTable,
			Columns: []string{imagecreationasset.DraftTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationtemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PublishedTemplatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imagecreationasset.PublishedTemplatesTable,
			Columns: []string{imagecreationasset.PublishedTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationtemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageCreationAsset.Create().
//		SetContent(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageCreationAssetUpsert) {
//			SetContent(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageCreationAssetCreate) OnConflict(opts ...sql.ConflictOption) *ImageCreationAssetUpsertOne {
	_c.conflict = opts
	return &ImageCreationAssetUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageCreationAsset.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageCreationAssetCreate) OnConflictColumns(columns ...string) *ImageCreationAssetUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageCreationAssetUpsertOne{
		create: _c,
	}
}

type (
	// ImageCreationAssetUpsertOne is the builder for "upsert"-ing
	//  one ImageCreationAsset node.
	ImageCreationAssetUpsertOne struct {
		create *ImageCreationAssetCreate
	}

	// ImageCreationAssetUpsert is the "OnConflict" setter.
	ImageCreationAssetUpsert struct {
		*sql.UpdateSet
	}
)

// SetContent sets the "content" field.
func (u *ImageCreationAssetUpsert) SetContent(v []byte) *ImageCreationAssetUpsert {
	u.Set(imagecreationasset.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ImageCreationAssetUpsert) UpdateContent() *ImageCreationAssetUpsert {
	u.SetExcluded(imagecreationasset.FieldContent)
	return u
}

// SetContentType sets the "content_type" field.
func (u *ImageCreationAssetUpsert) SetContentType(v string) *ImageCreationAssetUpsert {
	u.Set(imagecreationasset.FieldContentType, v)
	return u
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *ImageCreationAssetUpsert) UpdateContentType() *ImageCreationAssetUpsert {
	u.SetExcluded(imagecreationasset.FieldContentType)
	return u
}

// SetByteSize sets the "byte_size" field.
func (u *ImageCreationAssetUpsert) SetByteSize(v int) *ImageCreationAssetUpsert {
	u.Set(imagecreationasset.FieldByteSize, v)
	return u
}

// UpdateByteSize sets the "byte_size" field to the value that was provided on create.
func (u *ImageCreationAssetUpsert) UpdateByteSize() *ImageCreationAssetUpsert {
	u.SetExcluded(imagecreationasset.FieldByteSize)
	return u
}

// AddByteSize adds v to the "byte_size" field.
func (u *ImageCreationAssetUpsert) AddByteSize(v int) *ImageCreationAssetUpsert {
	u.Add(imagecreationasset.FieldByteSize, v)
	return u
}

// SetWidth sets the "width" field.
func (u *ImageCreationAssetUpsert) SetWidth(v int) *ImageCreationAssetUpsert {
	u.Set(imagecreationasset.FieldWidth, v)
	return u
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ImageCreationAssetUpsert) UpdateWidth() *ImageCreationAssetUpsert {
	u.SetExcluded(imagecreationasset.FieldWidth)
	return u
}

// AddWidth adds v to the "width" field.
func (u *ImageCreationAssetUpsert) AddWidth(v int) *ImageCreationAssetUpsert {
	u.Add(imagecreationasset.FieldWidth, v)
	return u
}

// SetHeight sets the "height" field.
func (u *ImageCreationAssetUpsert) SetHeight(v int) *ImageCreationAssetUpsert {
	u.Set(imagecreationasset.FieldHeight, v)
	return u
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ImageCreationAssetUpsert) UpdateHeight() *ImageCreationAssetUpsert {
	u.SetExcluded(imagecreationasset.FieldHeight)
	return u
}

// AddHeight adds v to the "height" field.
func (u *ImageCreationAssetUpsert) AddHeight(v int) *ImageCreationAssetUpsert {
	u.Add(imagecreationasset.FieldHeight, v)
	return u
}

// SetSourceType sets the "source_type" field.
func (u *ImageCreationAssetUpsert) SetSourceType(v string) *ImageCreationAssetUpsert {
	u.Set(imagecreationasset.FieldSourceType, v)
	return u
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *ImageCreationAssetUpsert) UpdateSourceType() *ImageCreationAssetUpsert {
	u.SetExcluded(imagecreationasset.FieldSourceType)
	return u
}

// SetSourceProvider sets the "source_provider" field.
func (u *ImageCreationAssetUpsert) SetSourceProvider(v string) *ImageCreationAssetUpsert {
	u.Set(imagecreationasset.FieldSourceProvider, v)
	return u
}

// UpdateSourceProvider sets the "source_provider" field to the value that was provided on create.
func (u *ImageCreationAssetUpsert) UpdateSourceProvider() *ImageCreationAssetUpsert {
	u.SetExcluded(imagecreationasset.FieldSourceProvider)
	return u
}

// ClearSourceProvider clears the value of the "source_provider" field.
func (u *ImageCreationAssetUpsert) ClearSourceProvider() *ImageCreationAssetUpsert {
	u.SetNull(imagecreationasset.FieldSourceProvider)
	return u
}

// SetSourceModel sets the "source_model" field.
func (u *ImageCreationAssetUpsert) SetSourceModel(v string) *ImageCreationAssetUpsert {
	u.Set(imagecreationasset.FieldSourceModel, v)
	return u
}

// UpdateSourceModel sets the "source_model" field to the value that was provided on create.
func (u *ImageCreationAssetUpsert) UpdateSourceModel() *ImageCreationAssetUpsert {
	u.SetExcluded(imagecreationasset.FieldSourceModel)
	return u
}

// ClearSourceModel clears the value of the "source_model" field.
func (u *ImageCreationAssetUpsert) ClearSourceModel() *ImageCreationAssetUpsert {
	u.SetNull(imagecreationasset.FieldSourceModel)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *ImageCreationAssetUpsert) SetCreatedBy(v int64) *ImageCreationAssetUpsert {
	u.Set(imagecreationasset.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ImageCreationAssetUpsert) UpdateCreatedBy() *ImageCreationAssetUpsert {
	u.SetExcluded(imagecreationasset.FieldCreatedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ImageCreationAsset.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(imagecreationasset.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ImageCreationAssetUpsertOne) UpdateNewValues() *ImageCreationAssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(imagecreationasset.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(imagecreationasset.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageCreationAsset.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ImageCreationAssetUpsertOne) Ignore() *ImageCreationAssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageCreationAssetUpsertOne) DoNothing() *ImageCreationAssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageCreationAssetCreate.OnConflict
// documentation for more info.
func (u *ImageCreationAssetUpsertOne) Update(set func(*ImageCreationAssetUpsert)) *ImageCreationAssetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageCreationAssetUpsert{UpdateSet: update})
	}))
	return u
}

// SetContent sets the "content" field.
func (u *ImageCreationAssetUpsertOne) SetContent(v []byte) *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ImageCreationAssetUpsertOne) UpdateContent() *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.UpdateContent()
	})
}

// SetContentType sets the "content_type" field.
func (u *ImageCreationAssetUpsertOne) SetContentType(v string) *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *ImageCreationAssetUpsertOne) UpdateContentType() *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.UpdateContentType()
	})
}

// SetByteSize sets the "byte_size" field.
func (u *ImageCreationAssetUpsertOne) SetByteSize(v int) *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.SetByteSize(v)
	})
}

// AddByteSize adds v to the "byte_size" field.
func (u *ImageCreationAssetUpsertOne) AddByteSize(v int) *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.AddByteSize(v)
	})
}

// UpdateByteSize sets the "byte_size" field to the value that was provided on create.
func (u *ImageCreationAssetUpsertOne) UpdateByteSize() *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.UpdateByteSize()
	})
}

// SetWidth sets the "width" field.
func (u *ImageCreationAssetUpsertOne) SetWidth(v int) *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *ImageCreationAssetUpsertOne) AddWidth(v int) *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ImageCreationAssetUpsertOne) UpdateWidth() *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.UpdateWidth()
	})
}

// SetHeight sets the "height" field.
func (u *ImageCreationAssetUpsertOne) SetHeight(v int) *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *ImageCreationAssetUpsertOne) AddHeight(v int) *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ImageCreationAssetUpsertOne) UpdateHeight() *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.UpdateHeight()
	})
}

// SetSourceType sets the "source_type" field.
func (u *ImageCreationAssetUpsertOne) SetSourceType(v string) *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *ImageCreationAssetUpsertOne) UpdateSourceType() *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceProvider sets the "source_provider" field.
func (u *ImageCreationAssetUpsertOne) SetSourceProvider(v string) *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.SetSourceProvider(v)
	})
}

// UpdateSourceProvider sets the "source_provider" field to the value that was provided on create.
func (u *ImageCreationAssetUpsertOne) UpdateSourceProvider() *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.UpdateSourceProvider()
	})
}

// ClearSourceProvider clears the value of the "source_provider" field.
func (u *ImageCreationAssetUpsertOne) ClearSourceProvider() *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.ClearSourceProvider()
	})
}

// SetSourceModel sets the "source_model" field.
func (u *ImageCreationAssetUpsertOne) SetSourceModel(v string) *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.SetSourceModel(v)
	})
}

// UpdateSourceModel sets the "source_model" field to the value that was provided on create.
func (u *ImageCreationAssetUpsertOne) UpdateSourceModel() *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.UpdateSourceModel()
	})
}

// ClearSourceModel clears the value of the "source_model" field.
func (u *ImageCreationAssetUpsertOne) ClearSourceModel() *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.ClearSourceModel()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ImageCreationAssetUpsertOne) SetCreatedBy(v int64) *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ImageCreationAssetUpsertOne) UpdateCreatedBy() *ImageCreationAssetUpsertOne {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *ImageCreationAssetUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageCreationAssetCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageCreationAssetUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ImageCreationAssetUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ImageCreationAssetUpsertOne.ID is not supported by MySQL driver. Use ImageCreationAssetUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ImageCreationAssetUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ImageCreationAssetCreateBulk is the builder for creating many ImageCreationAsset entities in bulk.
type ImageCreationAssetCreateBulk struct {
	config
	err      error
	builders []*ImageCreationAssetCreate
	conflict []sql.ConflictOption
}

// Save creates the ImageCreationAsset entities in the database.
func (_c *ImageCreationAssetCreateBulk) Save(ctx context.Context) ([]*ImageCreationAsset, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ImageCreationAsset, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImageCreationAssetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImageCreationAssetCreateBulk) SaveX(ctx context.Context) []*ImageCreationAsset {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageCreationAssetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageCreationAssetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageCreationAsset.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageCreationAssetUpsert) {
//			SetContent(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageCreationAssetCreateBulk) OnConflict(opts ...sql.ConflictOption) *ImageCreationAssetUpsertBulk {
	_c.conflict = opts
	return &ImageCreationAssetUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageCreationAsset.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageCreationAssetCreateBulk) OnConflictColumns(columns ...string) *ImageCreationAssetUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageCreationAssetUpsertBulk{
		create: _c,
	}
}

// ImageCreationAssetUpsertBulk is the builder for "upsert"-ing
// a bulk of ImageCreationAsset nodes.
type ImageCreationAssetUpsertBulk struct {
	create *ImageCreationAssetCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ImageCreationAsset.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(imagecreationasset.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ImageCreationAssetUpsertBulk) UpdateNewValues() *ImageCreationAssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(imagecreationasset.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(imagecreationasset.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageCreationAsset.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ImageCreationAssetUpsertBulk) Ignore() *ImageCreationAssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageCreationAssetUpsertBulk) DoNothing() *ImageCreationAssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageCreationAssetCreateBulk.OnConflict
// documentation for more info.
func (u *ImageCreationAssetUpsertBulk) Update(set func(*ImageCreationAssetUpsert)) *ImageCreationAssetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageCreationAssetUpsert{UpdateSet: update})
	}))
	return u
}

// SetContent sets the "content" field.
func (u *ImageCreationAssetUpsertBulk) SetContent(v []byte) *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ImageCreationAssetUpsertBulk) UpdateContent() *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.UpdateContent()
	})
}

// SetContentType sets the "content_type" field.
func (u *ImageCreationAssetUpsertBulk) SetContentType(v string) *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.SetContentType(v)
	})
}

// UpdateContentType sets the "content_type" field to the value that was provided on create.
func (u *ImageCreationAssetUpsertBulk) UpdateContentType() *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.UpdateContentType()
	})
}

// SetByteSize sets the "byte_size" field.
func (u *ImageCreationAssetUpsertBulk) SetByteSize(v int) *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.SetByteSize(v)
	})
}

// AddByteSize adds v to the "byte_size" field.
func (u *ImageCreationAssetUpsertBulk) AddByteSize(v int) *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.AddByteSize(v)
	})
}

// UpdateByteSize sets the "byte_size" field to the value that was provided on create.
func (u *ImageCreationAssetUpsertBulk) UpdateByteSize() *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.UpdateByteSize()
	})
}

// SetWidth sets the "width" field.
func (u *ImageCreationAssetUpsertBulk) SetWidth(v int) *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.SetWidth(v)
	})
}

// AddWidth adds v to the "width" field.
func (u *ImageCreationAssetUpsertBulk) AddWidth(v int) *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.AddWidth(v)
	})
}

// UpdateWidth sets the "width" field to the value that was provided on create.
func (u *ImageCreationAssetUpsertBulk) UpdateWidth() *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.UpdateWidth()
	})
}

// SetHeight sets the "height" field.
func (u *ImageCreationAssetUpsertBulk) SetHeight(v int) *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.SetHeight(v)
	})
}

// AddHeight adds v to the "height" field.
func (u *ImageCreationAssetUpsertBulk) AddHeight(v int) *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.AddHeight(v)
	})
}

// UpdateHeight sets the "height" field to the value that was provided on create.
func (u *ImageCreationAssetUpsertBulk) UpdateHeight() *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.UpdateHeight()
	})
}

// SetSourceType sets the "source_type" field.
func (u *ImageCreationAssetUpsertBulk) SetSourceType(v string) *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.SetSourceType(v)
	})
}

// UpdateSourceType sets the "source_type" field to the value that was provided on create.
func (u *ImageCreationAssetUpsertBulk) UpdateSourceType() *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.UpdateSourceType()
	})
}

// SetSourceProvider sets the "source_provider" field.
func (u *ImageCreationAssetUpsertBulk) SetSourceProvider(v string) *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.SetSourceProvider(v)
	})
}

// UpdateSourceProvider sets the "source_provider" field to the value that was provided on create.
func (u *ImageCreationAssetUpsertBulk) UpdateSourceProvider() *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.UpdateSourceProvider()
	})
}

// ClearSourceProvider clears the value of the "source_provider" field.
func (u *ImageCreationAssetUpsertBulk) ClearSourceProvider() *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.ClearSourceProvider()
	})
}

// SetSourceModel sets the "source_model" field.
func (u *ImageCreationAssetUpsertBulk) SetSourceModel(v string) *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.SetSourceModel(v)
	})
}

// UpdateSourceModel sets the "source_model" field to the value that was provided on create.
func (u *ImageCreationAssetUpsertBulk) UpdateSourceModel() *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.UpdateSourceModel()
	})
}

// ClearSourceModel clears the value of the "source_model" field.
func (u *ImageCreationAssetUpsertBulk) ClearSourceModel() *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.ClearSourceModel()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ImageCreationAssetUpsertBulk) SetCreatedBy(v int64) *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ImageCreationAssetUpsertBulk) UpdateCreatedBy() *ImageCreationAssetUpsertBulk {
	return u.Update(func(s *ImageCreationAssetUpsert) {
		s.UpdateCreatedBy()
	})
}

// Exec executes the query.
func (u *ImageCreationAssetUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ImageCreationAssetCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageCreationAssetCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageCreationAssetUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
