// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imagecreationasset"
	"github.com/Wei-Shaw/sub2api/ent/imagecreationtemplate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// ImageCreationTemplateUpdate is the builder for updating ImageCreationTemplate entities.
type ImageCreationTemplateUpdate struct {
	config
	hooks    []Hook
	mutation *ImageCreationTemplateMutation
}

// Where appends a list predicates to the ImageCreationTemplateUpdate builder.
func (_u *ImageCreationTemplateUpdate) Where(ps ...predicate.ImageCreationTemplate) *ImageCreationTemplateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetState sets the "state" field.
func (_u *ImageCreationTemplateUpdate) SetState(v string) *ImageCreationTemplateUpdate {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdate) SetNillableState(v *string) *ImageCreationTemplateUpdate {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetDraftData sets the "draft_data" field.
func (_u *ImageCreationTemplateUpdate) SetDraftData(v domain.ImageCreationTemplateDocument) *ImageCreationTemplateUpdate {
	_u.mutation.SetDraftData(v)
	return _u
}

// SetNillableDraftData sets the "draft_data" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdate) SetNillableDraftData(v *domain.ImageCreationTemplateDocument) *ImageCreationTemplateUpdate {
	if v != nil {
		_u.SetDraftData(*v)
	}
	return _u
}

// SetPublishedData sets the "published_data" field.
func (_u *ImageCreationTemplateUpdate) SetPublishedData(v *domain.ImageCreationTemplateDocument) *ImageCreationTemplateUpdate {
	_u.mutation.SetPublishedData(v)
	return _u
}

// ClearPublishedData clears the value of the "published_data" field.
func (_u *ImageCreationTemplateUpdate) ClearPublishedData() *ImageCreationTemplateUpdate {
	_u.mutation.ClearPublishedData()
	return _u
}

// SetRevision sets the "revision" field.
func (_u *ImageCreationTemplateUpdate) SetRevision(v int) *ImageCreationTemplateUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdate) SetNillableRevision(v *int) *ImageCreationTemplateUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *ImageCreationTemplateUpdate) AddRevision(v int) *ImageCreationTemplateUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// SetPublishedVersion sets the "published_version" field.
func (_u *ImageCreationTemplateUpdate) SetPublishedVersion(v int) *ImageCreationTemplateUpdate {
	_u.mutation.ResetPublishedVersion()
	_u.mutation.SetPublishedVersion(v)
	return _u
}

// SetNillablePublishedVersion sets the "published_version" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdate) SetNillablePublishedVersion(v *int) *ImageCreationTemplateUpdate {
	if v != nil {
		_u.SetPublishedVersion(*v)
	}
	return _u
}

// AddPublishedVersion adds value to the "published_version" field.
func (_u *ImageCreationTemplateUpdate) AddPublishedVersion(v int) *ImageCreationTemplateUpdate {
	_u.mutation.AddPublishedVersion(v)
	return _u
}

// SetDraftCoverAssetID sets the "draft_cover_asset_id" field.
func (_u *ImageCreationTemplateUpdate) SetDraftCoverAssetID(v string) *ImageCreationTemplateUpdate {
	_u.mutation.SetDraftCoverAssetID(v)
	return _u
}

// SetNillableDraftCoverAssetID sets the "draft_cover_asset_id" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdate) SetNillableDraftCoverAssetID(v *string) *ImageCreationTemplateUpdate {
	if v != nil {
		_u.SetDraftCoverAssetID(*v)
	}
	return _u
}

// ClearDraftCoverAssetID clears the value of the "draft_cover_asset_id" field.
func (_u *ImageCreationTemplateUpdate) ClearDraftCoverAssetID() *ImageCreationTemplateUpdate {
	_u.mutation.ClearDraftCoverAssetID()
	return _u
}

// SetPublishedCoverAssetID sets the "published_cover_asset_id" field.
func (_u *ImageCreationTemplateUpdate) SetPublishedCoverAssetID(v string) *ImageCreationTemplateUpdate {
	_u.mutation.SetPublishedCoverAssetID(v)
	return _u
}

// SetNillablePublishedCoverAssetID sets the "published_cover_asset_id" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdate) SetNillablePublishedCoverAssetID(v *string) *ImageCreationTemplateUpdate {
	if v != nil {
		_u.SetPublishedCoverAssetID(*v)
	}
	return _u
}

// ClearPublishedCoverAssetID clears the value of the "published_cover_asset_id" field.
func (_u *ImageCreationTemplateUpdate) ClearPublishedCoverAssetID() *ImageCreationTemplateUpdate {
	_u.mutation.ClearPublishedCoverAssetID()
	return _u
}

// SetHomePosition sets the "home_position" field.
func (_u *ImageCreationTemplateUpdate) SetHomePosition(v int16) *ImageCreationTemplateUpdate {
	_u.mutation.ResetHomePosition()
	_u.mutation.SetHomePosition(v)
	return _u
}

// SetNillableHomePosition sets the "home_position" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdate) SetNillableHomePosition(v *int16) *ImageCreationTemplateUpdate {
	if v != nil {
		_u.SetHomePosition(*v)
	}
	return _u
}

// AddHomePosition adds value to the "home_position" field.
func (_u *ImageCreationTemplateUpdate) AddHomePosition(v int16) *ImageCreationTemplateUpdate {
	_u.mutation.AddHomePosition(v)
	return _u
}

// ClearHomePosition clears the value of the "home_position" field.
func (_u *ImageCreationTemplateUpdate) ClearHomePosition() *ImageCreationTemplateUpdate {
	_u.mutation.ClearHomePosition()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ImageCreationTemplateUpdate) SetCreatedBy(v int64) *ImageCreationTemplateUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdate) SetNillableCreatedBy(v *int64) *ImageCreationTemplateUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ImageCreationTemplateUpdate) SetUpdatedBy(v int64) *ImageCreationTemplateUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdate) SetNillableUpdatedBy(v *int64) *ImageCreationTemplateUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageCreationTemplateUpdate) SetUpdatedAt(v time.Time) *ImageCreationTemplateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *ImageCreationTemplateUpdate) SetPublishedAt(v time.Time) *ImageCreationTemplateUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdate) SetNillablePublishedAt(v *time.Time) *ImageCreationTemplateUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *ImageCreationTemplateUpdate) ClearPublishedAt() *ImageCreationTemplateUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetDraftCoverID sets the "draft_cover" edge to the ImageCreationAsset entity by ID.
func (_u *ImageCreationTemplateUpdate) SetDraftCoverID(id string) *ImageCreationTemplateUpdate {
	_u.mutation.SetDraftCoverID(id)
	return _u
}

// SetNillableDraftCoverID sets the "draft_cover" edge to the ImageCreationAsset entity by ID if the given value is not nil.
func (_u *ImageCreationTemplateUpdate) SetNillableDraftCoverID(id *string) *ImageCreationTemplateUpdate {
	if id != nil {
		_u = _u.SetDraftCoverID(*id)
	}
	return _u
}

// SetDraftCover sets the "draft_cover" edge to the ImageCreationAsset entity.
func (_u *ImageCreationTemplateUpdate) SetDraftCover(v *ImageCreationAsset) *ImageCreationTemplateUpdate {
	return _u.SetDraftCoverID(v.ID)
}

// SetPublishedCoverID sets the "published_cover" edge to the ImageCreationAsset entity by ID.
func (_u *ImageCreationTemplateUpdate) SetPublishedCoverID(id string) *ImageCreationTemplateUpdate {
	_u.mutation.SetPublishedCoverID(id)
	return _u
}

// SetNillablePublishedCoverID sets the "published_cover" edge to the ImageCreationAsset entity by ID if the given value is not nil.
func (_u *ImageCreationTemplateUpdate) SetNillablePublishedCoverID(id *string) *ImageCreationTemplateUpdate {
	if id != nil {
		_u = _u.SetPublishedCoverID(*id)
	}
	return _u
}

// SetPublishedCover sets the "published_cover" edge to the ImageCreationAsset entity.
func (_u *ImageCreationTemplateUpdate) SetPublishedCover(v *ImageCreationAsset) *ImageCreationTemplateUpdate {
	return _u.SetPublishedCoverID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *ImageCreationTemplateUpdate) SetCreatorID(id int64) *ImageCreationTemplateUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *ImageCreationTemplateUpdate) SetCreator(v *User) *ImageCreationTemplateUpdate {
	return _u.SetCreatorID(v.ID)
}

// SetUpdaterID sets the "updater" edge to the User entity by ID.
func (_u *ImageCreationTemplateUpdate) SetUpdaterID(id int64) *ImageCreationTemplateUpdate {
	_u.mutation.SetUpdaterID(id)
	return _u
}

// SetUpdater sets the "updater" edge to the User entity.
func (_u *ImageCreationTemplateUpdate) SetUpdater(v *User) *ImageCreationTemplateUpdate {
	return _u.SetUpdaterID(v.ID)
}

// Mutation returns the ImageCreationTemplateMutation object of the builder.
func (_u *ImageCreationTemplateUpdate) Mutation() *ImageCreationTemplateMutation {
	return _u.mutation
}

// ClearDraftCover clears the "draft_cover" edge to the ImageCreationAsset entity.
func (_u *ImageCreationTemplateUpdate) ClearDraftCover() *ImageCreationTemplateUpdate {
	_u.mutation.ClearDraftCover()
	return _u
}

// ClearPublishedCover clears the "published_cover" edge to the ImageCreationAsset entity.
func (_u *ImageCreationTemplateUpdate) ClearPublishedCover() *ImageCreationTemplateUpdate {
	_u.mutation.ClearPublishedCover()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *ImageCreationTemplateUpdate) ClearCreator() *ImageCreationTemplateUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearUpdater clears the "updater" edge to the User entity.
func (_u *ImageCreationTemplateUpdate) ClearUpdater() *ImageCreationTemplateUpdate {
	_u.mutation.ClearUpdater()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImageCreationTemplateUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageCreationTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImageCreationTemplateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageCreationTemplateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageCreationTemplateUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := imagecreationtemplate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageCreationTemplateUpdate) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := imagecreationtemplate.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "ImageCreationTemplate.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := imagecreationtemplate.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "ImageCreationTemplate.revision": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublishedVersion(); ok {
		if err := imagecreationtemplate.PublishedVersionValidator(v); err != nil {
			return &ValidationError{Name: "published_version", err: fmt.Errorf(`ent: validator failed for field "ImageCreationTemplate.published_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DraftCoverAssetID(); ok {
		if err := imagecreationtemplate.DraftCoverAssetIDValidator(v); err != nil {
			return &ValidationError{Name: "draft_cover_asset_id", err: fmt.Errorf(`ent: validator failed for field "ImageCreationTemplate.draft_cover_asset_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublishedCoverAssetID(); ok {
		if err := imagecreationtemplate.PublishedCoverAssetIDValidator(v); err != nil {
			return &ValidationError{Name: "published_cover_asset_id", err: fmt.Errorf(`ent: validator failed for field "ImageCreationTemplate.published_cover_asset_id": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ImageCreationTemplate.creator"`)
	}
	if _u.mutation.UpdaterCleared() && len(_u.mutation.UpdaterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ImageCreationTemplate.updater"`)
	}
	return nil
}

func (_u *ImageCreationTemplateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imagecreationtemplate.Table, imagecreationtemplate.Columns, sqlgraph.NewFieldSpec(imagecreationtemplate.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(imagecreationtemplate.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.DraftData(); ok {
		_spec.SetField(imagecreationtemplate.FieldDraftData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.PublishedData(); ok {
		_spec.SetField(imagecreationtemplate.FieldPublishedData, field.TypeJSON, value)
	}
	if _u.mutation.PublishedDataCleared() {
		_spec.ClearField(imagecreationtemplate.FieldPublishedData, field.TypeJSON)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(imagecreationtemplate.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(imagecreationtemplate.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PublishedVersion(); ok {
		_spec.SetField(imagecreationtemplate.FieldPublishedVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPublishedVersion(); ok {
		_spec.AddField(imagecreationtemplate.FieldPublishedVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.HomePosition(); ok {
		_spec.SetField(imagecreationtemplate.FieldHomePosition, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedHomePosition(); ok {
		_spec.AddField(imagecreationtemplate.FieldHomePosition, field.TypeInt16, value)
	}
	if _u.mutation.HomePositionCleared() {
		_spec.ClearField(imagecreationtemplate.FieldHomePosition, field.TypeInt16)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imagecreationtemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(imagecreationtemplate.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(imagecreationtemplate.FieldPublishedAt, field.TypeTime)
	}
	if _u.mutation.DraftCoverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.DraftCoverTable,
			Columns: []string{imagecreationtemplate.DraftCoverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationasset.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DraftCoverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.DraftCoverTable,
			Columns: []string{imagecreationtemplate.DraftCoverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationasset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PublishedCoverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.PublishedCoverTable,
			Columns: []string{imagecreationtemplate.PublishedCoverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationasset.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PublishedCoverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.PublishedCoverTable,
			Columns: []string{imagecreationtemplate.PublishedCoverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationasset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.CreatorTable,
			Columns: []string{imagecreationtemplate.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.CreatorTable,
			Columns: []string{imagecreationtemplate.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UpdaterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.UpdaterTable,
			Columns: []string{imagecreationtemplate.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.UpdaterTable,
			Columns: []string{imagecreationtemplate.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imagecreationtemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImageCreationTemplateUpdateOne is the builder for updating a single ImageCreationTemplate entity.
type ImageCreationTemplateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageCreationTemplateMutation
}

// SetState sets the "state" field.
func (_u *ImageCreationTemplateUpdateOne) SetState(v string) *ImageCreationTemplateUpdateOne {
	_u.mutation.SetState(v)
	return _u
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdateOne) SetNillableState(v *string) *ImageCreationTemplateUpdateOne {
	if v != nil {
		_u.SetState(*v)
	}
	return _u
}

// SetDraftData sets the "draft_data" field.
func (_u *ImageCreationTemplateUpdateOne) SetDraftData(v domain.ImageCreationTemplateDocument) *ImageCreationTemplateUpdateOne {
	_u.mutation.SetDraftData(v)
	return _u
}

// SetNillableDraftData sets the "draft_data" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdateOne) SetNillableDraftData(v *domain.ImageCreationTemplateDocument) *ImageCreationTemplateUpdateOne {
	if v != nil {
		_u.SetDraftData(*v)
	}
	return _u
}

// SetPublishedData sets the "published_data" field.
func (_u *ImageCreationTemplateUpdateOne) SetPublishedData(v *domain.ImageCreationTemplateDocument) *ImageCreationTemplateUpdateOne {
	_u.mutation.SetPublishedData(v)
	return _u
}

// ClearPublishedData clears the value of the "published_data" field.
func (_u *ImageCreationTemplateUpdateOne) ClearPublishedData() *ImageCreationTemplateUpdateOne {
	_u.mutation.ClearPublishedData()
	return _u
}

// SetRevision sets the "revision" field.
func (_u *ImageCreationTemplateUpdateOne) SetRevision(v int) *ImageCreationTemplateUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdateOne) SetNillableRevision(v *int) *ImageCreationTemplateUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *ImageCreationTemplateUpdateOne) AddRevision(v int) *ImageCreationTemplateUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// SetPublishedVersion sets the "published_version" field.
func (_u *ImageCreationTemplateUpdateOne) SetPublishedVersion(v int) *ImageCreationTemplateUpdateOne {
	_u.mutation.ResetPublishedVersion()
	_u.mutation.SetPublishedVersion(v)
	return _u
}

// SetNillablePublishedVersion sets the "published_version" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdateOne) SetNillablePublishedVersion(v *int) *ImageCreationTemplateUpdateOne {
	if v != nil {
		_u.SetPublishedVersion(*v)
	}
	return _u
}

// AddPublishedVersion adds value to the "published_version" field.
func (_u *ImageCreationTemplateUpdateOne) AddPublishedVersion(v int) *ImageCreationTemplateUpdateOne {
	_u.mutation.AddPublishedVersion(v)
	return _u
}

// SetDraftCoverAssetID sets the "draft_cover_asset_id" field.
func (_u *ImageCreationTemplateUpdateOne) SetDraftCoverAssetID(v string) *ImageCreationTemplateUpdateOne {
	_u.mutation.SetDraftCoverAssetID(v)
	return _u
}

// SetNillableDraftCoverAssetID sets the "draft_cover_asset_id" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdateOne) SetNillableDraftCoverAssetID(v *string) *ImageCreationTemplateUpdateOne {
	if v != nil {
		_u.SetDraftCoverAssetID(*v)
	}
	return _u
}

// ClearDraftCoverAssetID clears the value of the "draft_cover_asset_id" field.
func (_u *ImageCreationTemplateUpdateOne) ClearDraftCoverAssetID() *ImageCreationTemplateUpdateOne {
	_u.mutation.ClearDraftCoverAssetID()
	return _u
}

// SetPublishedCoverAssetID sets the "published_cover_asset_id" field.
func (_u *ImageCreationTemplateUpdateOne) SetPublishedCoverAssetID(v string) *ImageCreationTemplateUpdateOne {
	_u.mutation.SetPublishedCoverAssetID(v)
	return _u
}

// SetNillablePublishedCoverAssetID sets the "published_cover_asset_id" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdateOne) SetNillablePublishedCoverAssetID(v *string) *ImageCreationTemplateUpdateOne {
	if v != nil {
		_u.SetPublishedCoverAssetID(*v)
	}
	return _u
}

// ClearPublishedCoverAssetID clears the value of the "published_cover_asset_id" field.
func (_u *ImageCreationTemplateUpdateOne) ClearPublishedCoverAssetID() *ImageCreationTemplateUpdateOne {
	_u.mutation.ClearPublishedCoverAssetID()
	return _u
}

// SetHomePosition sets the "home_position" field.
func (_u *ImageCreationTemplateUpdateOne) SetHomePosition(v int16) *ImageCreationTemplateUpdateOne {
	_u.mutation.ResetHomePosition()
	_u.mutation.SetHomePosition(v)
	return _u
}

// SetNillableHomePosition sets the "home_position" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdateOne) SetNillableHomePosition(v *int16) *ImageCreationTemplateUpdateOne {
	if v != nil {
		_u.SetHomePosition(*v)
	}
	return _u
}

// AddHomePosition adds value to the "home_position" field.
func (_u *ImageCreationTemplateUpdateOne) AddHomePosition(v int16) *ImageCreationTemplateUpdateOne {
	_u.mutation.AddHomePosition(v)
	return _u
}

// ClearHomePosition clears the value of the "home_position" field.
func (_u *ImageCreationTemplateUpdateOne) ClearHomePosition() *ImageCreationTemplateUpdateOne {
	_u.mutation.ClearHomePosition()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ImageCreationTemplateUpdateOne) SetCreatedBy(v int64) *ImageCreationTemplateUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdateOne) SetNillableCreatedBy(v *int64) *ImageCreationTemplateUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ImageCreationTemplateUpdateOne) SetUpdatedBy(v int64) *ImageCreationTemplateUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdateOne) SetNillableUpdatedBy(v *int64) *ImageCreationTemplateUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ImageCreationTemplateUpdateOne) SetUpdatedAt(v time.Time) *ImageCreationTemplateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *ImageCreationTemplateUpdateOne) SetPublishedAt(v time.Time) *ImageCreationTemplateUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *ImageCreationTemplateUpdateOne) SetNillablePublishedAt(v *time.Time) *ImageCreationTemplateUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *ImageCreationTemplateUpdateOne) ClearPublishedAt() *ImageCreationTemplateUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetDraftCoverID sets the "draft_cover" edge to the ImageCreationAsset entity by ID.
func (_u *ImageCreationTemplateUpdateOne) SetDraftCoverID(id string) *ImageCreationTemplateUpdateOne {
	_u.mutation.SetDraftCoverID(id)
	return _u
}

// SetNillableDraftCoverID sets the "draft_cover" edge to the ImageCreationAsset entity by ID if the given value is not nil.
func (_u *ImageCreationTemplateUpdateOne) SetNillableDraftCoverID(id *string) *ImageCreationTemplateUpdateOne {
	if id != nil {
		_u = _u.SetDraftCoverID(*id)
	}
	return _u
}

// SetDraftCover sets the "draft_cover" edge to the ImageCreationAsset entity.
func (_u *ImageCreationTemplateUpdateOne) SetDraftCover(v *ImageCreationAsset) *ImageCreationTemplateUpdateOne {
	return _u.SetDraftCoverID(v.ID)
}

// SetPublishedCoverID sets the "published_cover" edge to the ImageCreationAsset entity by ID.
func (_u *ImageCreationTemplateUpdateOne) SetPublishedCoverID(id string) *ImageCreationTemplateUpdateOne {
	_u.mutation.SetPublishedCoverID(id)
	return _u
}

// SetNillablePublishedCoverID sets the "published_cover" edge to the ImageCreationAsset entity by ID if the given value is not nil.
func (_u *ImageCreationTemplateUpdateOne) SetNillablePublishedCoverID(id *string) *ImageCreationTemplateUpdateOne {
	if id != nil {
		_u = _u.SetPublishedCoverID(*id)
	}
	return _u
}

// SetPublishedCover sets the "published_cover" edge to the ImageCreationAsset entity.
func (_u *ImageCreationTemplateUpdateOne) SetPublishedCover(v *ImageCreationAsset) *ImageCreationTemplateUpdateOne {
	return _u.SetPublishedCoverID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *ImageCreationTemplateUpdateOne) SetCreatorID(id int64) *ImageCreationTemplateUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *ImageCreationTemplateUpdateOne) SetCreator(v *User) *ImageCreationTemplateUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// SetUpdaterID sets the "updater" edge to the User entity by ID.
func (_u *ImageCreationTemplateUpdateOne) SetUpdaterID(id int64) *ImageCreationTemplateUpdateOne {
	_u.mutation.SetUpdaterID(id)
	return _u
}

// SetUpdater sets the "updater" edge to the User entity.
func (_u *ImageCreationTemplateUpdateOne) SetUpdater(v *User) *ImageCreationTemplateUpdateOne {
	return _u.SetUpdaterID(v.ID)
}

// Mutation returns the ImageCreationTemplateMutation object of the builder.
func (_u *ImageCreationTemplateUpdateOne) Mutation() *ImageCreationTemplateMutation {
	return _u.mutation
}

// ClearDraftCover clears the "draft_cover" edge to the ImageCreationAsset entity.
func (_u *ImageCreationTemplateUpdateOne) ClearDraftCover() *ImageCreationTemplateUpdateOne {
	_u.mutation.ClearDraftCover()
	return _u
}

// ClearPublishedCover clears the "published_cover" edge to the ImageCreationAsset entity.
func (_u *ImageCreationTemplateUpdateOne) ClearPublishedCover() *ImageCreationTemplateUpdateOne {
	_u.mutation.ClearPublishedCover()
	return _u
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *ImageCreationTemplateUpdateOne) ClearCreator() *ImageCreationTemplateUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearUpdater clears the "updater" edge to the User entity.
func (_u *ImageCreationTemplateUpdateOne) ClearUpdater() *ImageCreationTemplateUpdateOne {
	_u.mutation.ClearUpdater()
	return _u
}

// Where appends a list predicates to the ImageCreationTemplateUpdate builder.
func (_u *ImageCreationTemplateUpdateOne) Where(ps ...predicate.ImageCreationTemplate) *ImageCreationTemplateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImageCreationTemplateUpdateOne) Select(field string, fields ...string) *ImageCreationTemplateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ImageCreationTemplate entity.
func (_u *ImageCreationTemplateUpdateOne) Save(ctx context.Context) (*ImageCreationTemplate, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageCreationTemplateUpdateOne) SaveX(ctx context.Context) *ImageCreationTemplate {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImageCreationTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageCreationTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ImageCreationTemplateUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := imagecreationtemplate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageCreationTemplateUpdateOne) check() error {
	if v, ok := _u.mutation.State(); ok {
		if err := imagecreationtemplate.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "ImageCreationTemplate.state": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Revision(); ok {
		if err := imagecreationtemplate.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "ImageCreationTemplate.revision": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublishedVersion(); ok {
		if err := imagecreationtemplate.PublishedVersionValidator(v); err != nil {
			return &ValidationError{Name: "published_version", err: fmt.Errorf(`ent: validator failed for field "ImageCreationTemplate.published_version": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DraftCoverAssetID(); ok {
		if err := imagecreationtemplate.DraftCoverAssetIDValidator(v); err != nil {
			return &ValidationError{Name: "draft_cover_asset_id", err: fmt.Errorf(`ent: validator failed for field "ImageCreationTemplate.draft_cover_asset_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublishedCoverAssetID(); ok {
		if err := imagecreationtemplate.PublishedCoverAssetIDValidator(v); err != nil {
			return &ValidationError{Name: "published_cover_asset_id", err: fmt.Errorf(`ent: validator failed for field "ImageCreationTemplate.published_cover_asset_id": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ImageCreationTemplate.creator"`)
	}
	if _u.mutation.UpdaterCleared() && len(_u.mutation.UpdaterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ImageCreationTemplate.updater"`)
	}
	return nil
}

func (_u *ImageCreationTemplateUpdateOne) sqlSave(ctx context.Context) (_node *ImageCreationTemplate, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imagecreationtemplate.Table, imagecreationtemplate.Columns, sqlgraph.NewFieldSpec(imagecreationtemplate.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ImageCreationTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imagecreationtemplate.FieldID)
		for _, f := range fields {
			if !imagecreationtemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != imagecreationtemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.State(); ok {
		_spec.SetField(imagecreationtemplate.FieldState, field.TypeString, value)
	}
	if value, ok := _u.mutation.DraftData(); ok {
		_spec.SetField(imagecreationtemplate.FieldDraftData, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.PublishedData(); ok {
		_spec.SetField(imagecreationtemplate.FieldPublishedData, field.TypeJSON, value)
	}
	if _u.mutation.PublishedDataCleared() {
		_spec.ClearField(imagecreationtemplate.FieldPublishedData, field.TypeJSON)
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(imagecreationtemplate.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(imagecreationtemplate.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PublishedVersion(); ok {
		_spec.SetField(imagecreationtemplate.FieldPublishedVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPublishedVersion(); ok {
		_spec.AddField(imagecreationtemplate.FieldPublishedVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.HomePosition(); ok {
		_spec.SetField(imagecreationtemplate.FieldHomePosition, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedHomePosition(); ok {
		_spec.AddField(imagecreationtemplate.FieldHomePosition, field.TypeInt16, value)
	}
	if _u.mutation.HomePositionCleared() {
		_spec.ClearField(imagecreationtemplate.FieldHomePosition, field.TypeInt16)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(imagecreationtemplate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(imagecreationtemplate.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(imagecreationtemplate.FieldPublishedAt, field.TypeTime)
	}
	if _u.mutation.DraftCoverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.DraftCoverTable,
			Columns: []string{imagecreationtemplate.DraftCoverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationasset.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DraftCoverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.DraftCoverTable,
			Columns: []string{imagecreationtemplate.DraftCoverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationasset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PublishedCoverCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.PublishedCoverTable,
			Columns: []string{imagecreationtemplate.PublishedCoverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationasset.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PublishedCoverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.PublishedCoverTable,
			Columns: []string{imagecreationtemplate.PublishedCoverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationasset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.CreatorTable,
			Columns: []string{imagecreationtemplate.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.CreatorTable,
			Columns: []string{imagecreationtemplate.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UpdaterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.UpdaterTable,
			Columns: []string{imagecreationtemplate.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.UpdaterTable,
			Columns: []string{imagecreationtemplate.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ImageCreationTemplate{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imagecreationtemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
