// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imagecreationchangelog"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ImageCreationChangeLogDelete is the builder for deleting a ImageCreationChangeLog entity.
type ImageCreationChangeLogDelete struct {
	config
	hooks    []Hook
	mutation *ImageCreationChangeLogMutation
}

// Where appends a list predicates to the ImageCreationChangeLogDelete builder.
func (_d *ImageCreationChangeLogDelete) Where(ps ...predicate.ImageCreationChangeLog) *ImageCreationChangeLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ImageCreationChangeLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ImageCreationChangeLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ImageCreationChangeLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(imagecreationchangelog.Table, sqlgraph.NewFieldSpec(imagecreationchangelog.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ImageCreationChangeLogDeleteOne is the builder for deleting a single ImageCreationChangeLog entity.
type ImageCreationChangeLogDeleteOne struct {
	_d *ImageCreationChangeLogDelete
}

// Where appends a list predicates to the ImageCreationChangeLogDelete builder.
func (_d *ImageCreationChangeLogDeleteOne) Where(ps ...predicate.ImageCreationChangeLog) *ImageCreationChangeLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ImageCreationChangeLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{imagecreationchangelog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ImageCreationChangeLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
