// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imagecreationasset"
	"github.com/Wei-Shaw/sub2api/ent/imagecreationtemplate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// ImageCreationTemplateCreate is the builder for creating a ImageCreationTemplate entity.
type ImageCreationTemplateCreate struct {
	config
	mutation *ImageCreationTemplateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetState sets the "state" field.
func (_c *ImageCreationTemplateCreate) SetState(v string) *ImageCreationTemplateCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *ImageCreationTemplateCreate) SetNillableState(v *string) *ImageCreationTemplateCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetDraftData sets the "draft_data" field.
func (_c *ImageCreationTemplateCreate) SetDraftData(v domain.ImageCreationTemplateDocument) *ImageCreationTemplateCreate {
	_c.mutation.SetDraftData(v)
	return _c
}

// SetPublishedData sets the "published_data" field.
func (_c *ImageCreationTemplateCreate) SetPublishedData(v *domain.ImageCreationTemplateDocument) *ImageCreationTemplateCreate {
	_c.mutation.SetPublishedData(v)
	return _c
}

// SetRevision sets the "revision" field.
func (_c *ImageCreationTemplateCreate) SetRevision(v int) *ImageCreationTemplateCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_c *ImageCreationTemplateCreate) SetNillableRevision(v *int) *ImageCreationTemplateCreate {
	if v != nil {
		_c.SetRevision(*v)
	}
	return _c
}

// SetPublishedVersion sets the "published_version" field.
func (_c *ImageCreationTemplateCreate) SetPublishedVersion(v int) *ImageCreationTemplateCreate {
	_c.mutation.SetPublishedVersion(v)
	return _c
}

// SetNillablePublishedVersion sets the "published_version" field if the given value is not nil.
func (_c *ImageCreationTemplateCreate) SetNillablePublishedVersion(v *int) *ImageCreationTemplateCreate {
	if v != nil {
		_c.SetPublishedVersion(*v)
	}
	return _c
}

// SetDraftCoverAssetID sets the "draft_cover_asset_id" field.
func (_c *ImageCreationTemplateCreate) SetDraftCoverAssetID(v string) *ImageCreationTemplateCreate {
	_c.mutation.SetDraftCoverAssetID(v)
	return _c
}

// SetNillableDraftCoverAssetID sets the "draft_cover_asset_id" field if the given value is not nil.
func (_c *ImageCreationTemplateCreate) SetNillableDraftCoverAssetID(v *string) *ImageCreationTemplateCreate {
	if v != nil {
		_c.SetDraftCoverAssetID(*v)
	}
	return _c
}

// SetPublishedCoverAssetID sets the "published_cover_asset_id" field.
func (_c *ImageCreationTemplateCreate) SetPublishedCoverAssetID(v string) *ImageCreationTemplateCreate {
	_c.mutation.SetPublishedCoverAssetID(v)
	return _c
}

// SetNillablePublishedCoverAssetID sets the "published_cover_asset_id" field if the given value is not nil.
func (_c *ImageCreationTemplateCreate) SetNillablePublishedCoverAssetID(v *string) *ImageCreationTemplateCreate {
	if v != nil {
		_c.SetPublishedCoverAssetID(*v)
	}
	return _c
}

// SetHomePosition sets the "home_position" field.
func (_c *ImageCreationTemplateCreate) SetHomePosition(v int16) *ImageCreationTemplateCreate {
	_c.mutation.SetHomePosition(v)
	return _c
}

// SetNillableHomePosition sets the "home_position" field if the given value is not nil.
func (_c *ImageCreationTemplateCreate) SetNillableHomePosition(v *int16) *ImageCreationTemplateCreate {
	if v != nil {
		_c.SetHomePosition(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *ImageCreationTemplateCreate) SetCreatedBy(v int64) *ImageCreationTemplateCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ImageCreationTemplateCreate) SetUpdatedBy(v int64) *ImageCreationTemplateCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ImageCreationTemplateCreate) SetCreatedAt(v time.Time) *ImageCreationTemplateCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ImageCreationTemplateCreate) SetNillableCreatedAt(v *time.Time) *ImageCreationTemplateCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ImageCreationTemplateCreate) SetUpdatedAt(v time.Time) *ImageCreationTemplateCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ImageCreationTemplateCreate) SetNillableUpdatedAt(v *time.Time) *ImageCreationTemplateCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *ImageCreationTemplateCreate) SetPublishedAt(v time.Time) *ImageCreationTemplateCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *ImageCreationTemplateCreate) SetNillablePublishedAt(v *time.Time) *ImageCreationTemplateCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetDraftCoverID sets the "draft_cover" edge to the ImageCreationAsset entity by ID.
func (_c *ImageCreationTemplateCreate) SetDraftCoverID(id string) *ImageCreationTemplateCreate {
	_c.mutation.SetDraftCoverID(id)
	return _c
}

// SetNillableDraftCoverID sets the "draft_cover" edge to the ImageCreationAsset entity by ID if the given value is not nil.
func (_c *ImageCreationTemplateCreate) SetNillableDraftCoverID(id *string) *ImageCreationTemplateCreate {
	if id != nil {
		_c = _c.SetDraftCoverID(*id)
	}
	return _c
}

// SetDraftCover sets the "draft_cover" edge to the ImageCreationAsset entity.
func (_c *ImageCreationTemplateCreate) SetDraftCover(v *ImageCreationAsset) *ImageCreationTemplateCreate {
	return _c.SetDraftCoverID(v.ID)
}

// SetPublishedCoverID sets the "published_cover" edge to the ImageCreationAsset entity by ID.
func (_c *ImageCreationTemplateCreate) SetPublishedCoverID(id string) *ImageCreationTemplateCreate {
	_c.mutation.SetPublishedCoverID(id)
	return _c
}

// SetNillablePublishedCoverID sets the "published_cover" edge to the ImageCreationAsset entity by ID if the given value is not nil.
func (_c *ImageCreationTemplateCreate) SetNillablePublishedCoverID(id *string) *ImageCreationTemplateCreate {
	if id != nil {
		_c = _c.SetPublishedCoverID(*id)
	}
	return _c
}

// SetPublishedCover sets the "published_cover" edge to the ImageCreationAsset entity.
func (_c *ImageCreationTemplateCreate) SetPublishedCover(v *ImageCreationAsset) *ImageCreationTemplateCreate {
	return _c.SetPublishedCoverID(v.ID)
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *ImageCreationTemplateCreate) SetCreatorID(id int64) *ImageCreationTemplateCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *ImageCreationTemplateCreate) SetCreator(v *User) *ImageCreationTemplateCreate {
	return _c.SetCreatorID(v.ID)
}

// SetUpdaterID sets the "updater" edge to the User entity by ID.
func (_c *ImageCreationTemplateCreate) SetUpdaterID(id int64) *ImageCreationTemplateCreate {
	_c.mutation.SetUpdaterID(id)
	return _c
}

// SetUpdater sets the "updater" edge to the User entity.
func (_c *ImageCreationTemplateCreate) SetUpdater(v *User) *ImageCreationTemplateCreate {
	return _c.SetUpdaterID(v.ID)
}

// Mutation returns the ImageCreationTemplateMutation object of the builder.
func (_c *ImageCreationTemplateCreate) Mutation() *ImageCreationTemplateMutation {
	return _c.mutation
}

// Save creates the ImageCreationTemplate in the database.
func (_c *ImageCreationTemplateCreate) Save(ctx context.Context) (*ImageCreationTemplate, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ImageCreationTemplateCreate) SaveX(ctx context.Context) *ImageCreationTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageCreationTemplateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageCreationTemplateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ImageCreationTemplateCreate) defaults() {
	if _, ok := _c.mutation.State(); !ok {
		v := imagecreationtemplate.DefaultState
		_c.mutation.SetState(v)
	}
	if _, ok := _c.mutation.Revision(); !ok {
		v := imagecreationtemplate.DefaultRevision
		_c.mutation.SetRevision(v)
	}
	if _, ok := _c.mutation.PublishedVersion(); !ok {
		v := imagecreationtemplate.DefaultPublishedVersion
		_c.mutation.SetPublishedVersion(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := imagecreationtemplate.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := imagecreationtemplate.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ImageCreationTemplateCreate) check() error {
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "ImageCreationTemplate.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := imagecreationtemplate.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "ImageCreationTemplate.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DraftData(); !ok {
		return &ValidationError{Name: "draft_data", err: errors.New(`ent: missing required field "ImageCreationTemplate.draft_data"`)}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "ImageCreationTemplate.revision"`)}
	}
	if v, ok := _c.mutation.Revision(); ok {
		if err := imagecreationtemplate.RevisionValidator(v); err != nil {
			return &ValidationError{Name: "revision", err: fmt.Errorf(`ent: validator failed for field "ImageCreationTemplate.revision": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PublishedVersion(); !ok {
		return &ValidationError{Name: "published_version", err: errors.New(`ent: missing required field "ImageCreationTemplate.published_version"`)}
	}
	if v, ok := _c.mutation.PublishedVersion(); ok {
		if err := imagecreationtemplate.PublishedVersionValidator(v); err != nil {
			return &ValidationError{Name: "published_version", err: fmt.Errorf(`ent: validator failed for field "ImageCreationTemplate.published_version": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DraftCoverAssetID(); ok {
		if err := imagecreationtemplate.DraftCoverAssetIDValidator(v); err != nil {
			return &ValidationError{Name: "draft_cover_asset_id", err: fmt.Errorf(`ent: validator failed for field "ImageCreationTemplate.draft_cover_asset_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.PublishedCoverAssetID(); ok {
		if err := imagecreationtemplate.PublishedCoverAssetIDValidator(v); err != nil {
			return &ValidationError{Name: "published_cover_asset_id", err: fmt.Errorf(`ent: validator failed for field "ImageCreationTemplate.published_cover_asset_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "ImageCreationTemplate.created_by"`)}
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "ImageCreationTemplate.updated_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ImageCreationTemplate.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ImageCreationTemplate.updated_at"`)}
	}
	if len(_c.mutation.CreatorIDs()) == 0 {
		return &ValidationError{Name: "creator", err: errors.New(`ent: missing required edge "ImageCreationTemplate.creator"`)}
	}
	if len(_c.mutation.UpdaterIDs()) == 0 {
		return &ValidationError{Name: "updater", err: errors.New(`ent: missing required edge "ImageCreationTemplate.updater"`)}
	}
	return nil
}

func (_c *ImageCreationTemplateCreate) sqlSave(ctx context.Context) (*ImageCreationTemplate, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ImageCreationTemplateCreate) createSpec() (*ImageCreationTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &ImageCreationTemplate{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(imagecreationtemplate.Table, sqlgraph.NewFieldSpec(imagecreationtemplate.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(imagecreationtemplate.FieldState, field.TypeString, value)
		_node.State = value
	}
	if value, ok := _c.mutation.DraftData(); ok {
		_spec.SetField(imagecreationtemplate.FieldDraftData, field.TypeJSON, value)
		_node.DraftData = value
	}
	if value, ok := _c.mutation.PublishedData(); ok {
		_spec.SetField(imagecreationtemplate.FieldPublishedData, field.TypeJSON, value)
		_node.PublishedData = value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(imagecreationtemplate.FieldRevision, field.TypeInt, value)
		_node.Revision = value
	}
	if value, ok := _c.mutation.PublishedVersion(); ok {
		_spec.SetField(imagecreationtemplate.FieldPublishedVersion, field.TypeInt, value)
		_node.PublishedVersion = value
	}
	if value, ok := _c.mutation.HomePosition(); ok {
		_spec.SetField(imagecreationtemplate.FieldHomePosition, field.TypeInt16, value)
		_node.HomePosition = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(imagecreationtemplate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(imagecreationtemplate.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(imagecreationtemplate.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if nodes := _c.mutation.DraftCoverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.DraftCoverTable,
			Columns: []string{imagecreationtemplate.DraftCoverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationasset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.DraftCoverAssetID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PublishedCoverIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.PublishedCoverTable,
			Columns: []string{imagecreationtemplate.PublishedCoverColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationasset.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PublishedCoverAssetID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.CreatorTable,
			Columns: []string{imagecreationtemplate.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UpdaterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationtemplate.UpdaterTable,
			Columns: []string{imagecreationtemplate.UpdaterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UpdatedBy = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageCreationTemplate.Create().
//		SetState(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageCreationTemplateUpsert) {
//			SetState(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageCreationTemplateCreate) OnConflict(opts ...sql.ConflictOption) *ImageCreationTemplateUpsertOne {
	_c.conflict = opts
	return &ImageCreationTemplateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageCreationTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageCreationTemplateCreate) OnConflictColumns(columns ...string) *ImageCreationTemplateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageCreationTemplateUpsertOne{
		create: _c,
	}
}

type (
	// ImageCreationTemplateUpsertOne is the builder for "upsert"-ing
	//  one ImageCreationTemplate node.
	ImageCreationTemplateUpsertOne struct {
		create *ImageCreationTemplateCreate
	}

	// ImageCreationTemplateUpsert is the "OnConflict" setter.
	ImageCreationTemplateUpsert struct {
		*sql.UpdateSet
	}
)

// SetState sets the "state" field.
func (u *ImageCreationTemplateUpsert) SetState(v string) *ImageCreationTemplateUpsert {
	u.Set(imagecreationtemplate.FieldState, v)
	return u
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsert) UpdateState() *ImageCreationTemplateUpsert {
	u.SetExcluded(imagecreationtemplate.FieldState)
	return u
}

// SetDraftData sets the "draft_data" field.
func (u *ImageCreationTemplateUpsert) SetDraftData(v domain.ImageCreationTemplateDocument) *ImageCreationTemplateUpsert {
	u.Set(imagecreationtemplate.FieldDraftData, v)
	return u
}

// UpdateDraftData sets the "draft_data" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsert) UpdateDraftData() *ImageCreationTemplateUpsert {
	u.SetExcluded(imagecreationtemplate.FieldDraftData)
	return u
}

// SetPublishedData sets the "published_data" field.
func (u *ImageCreationTemplateUpsert) SetPublishedData(v *domain.ImageCreationTemplateDocument) *ImageCreationTemplateUpsert {
	u.Set(imagecreationtemplate.FieldPublishedData, v)
	return u
}

// UpdatePublishedData sets the "published_data" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsert) UpdatePublishedData() *ImageCreationTemplateUpsert {
	u.SetExcluded(imagecreationtemplate.FieldPublishedData)
	return u
}

// ClearPublishedData clears the value of the "published_data" field.
func (u *ImageCreationTemplateUpsert) ClearPublishedData() *ImageCreationTemplateUpsert {
	u.SetNull(imagecreationtemplate.FieldPublishedData)
	return u
}

// SetRevision sets the "revision" field.
func (u *ImageCreationTemplateUpsert) SetRevision(v int) *ImageCreationTemplateUpsert {
	u.Set(imagecreationtemplate.FieldRevision, v)
	return u
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsert) UpdateRevision() *ImageCreationTemplateUpsert {
	u.SetExcluded(imagecreationtemplate.FieldRevision)
	return u
}

// AddRevision adds v to the "revision" field.
func (u *ImageCreationTemplateUpsert) AddRevision(v int) *ImageCreationTemplateUpsert {
	u.Add(imagecreationtemplate.FieldRevision, v)
	return u
}

// SetPublishedVersion sets the "published_version" field.
func (u *ImageCreationTemplateUpsert) SetPublishedVersion(v int) *ImageCreationTemplateUpsert {
	u.Set(imagecreationtemplate.FieldPublishedVersion, v)
	return u
}

// UpdatePublishedVersion sets the "published_version" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsert) UpdatePublishedVersion() *ImageCreationTemplateUpsert {
	u.SetExcluded(imagecreationtemplate.FieldPublishedVersion)
	return u
}

// AddPublishedVersion adds v to the "published_version" field.
func (u *ImageCreationTemplateUpsert) AddPublishedVersion(v int) *ImageCreationTemplateUpsert {
	u.Add(imagecreationtemplate.FieldPublishedVersion, v)
	return u
}

// SetDraftCoverAssetID sets the "draft_cover_asset_id" field.
func (u *ImageCreationTemplateUpsert) SetDraftCoverAssetID(v string) *ImageCreationTemplateUpsert {
	u.Set(imagecreationtemplate.FieldDraftCoverAssetID, v)
	return u
}

// UpdateDraftCoverAssetID sets the "draft_cover_asset_id" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsert) UpdateDraftCoverAssetID() *ImageCreationTemplateUpsert {
	u.SetExcluded(imagecreationtemplate.FieldDraftCoverAssetID)
	return u
}

// ClearDraftCoverAssetID clears the value of the "draft_cover_asset_id" field.
func (u *ImageCreationTemplateUpsert) ClearDraftCoverAssetID() *ImageCreationTemplateUpsert {
	u.SetNull(imagecreationtemplate.FieldDraftCoverAssetID)
	return u
}

// SetPublishedCoverAssetID sets the "published_cover_asset_id" field.
func (u *ImageCreationTemplateUpsert) SetPublishedCoverAssetID(v string) *ImageCreationTemplateUpsert {
	u.Set(imagecreationtemplate.FieldPublishedCoverAssetID, v)
	return u
}

// UpdatePublishedCoverAssetID sets the "published_cover_asset_id" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsert) UpdatePublishedCoverAssetID() *ImageCreationTemplateUpsert {
	u.SetExcluded(imagecreationtemplate.FieldPublishedCoverAssetID)
	return u
}

// ClearPublishedCoverAssetID clears the value of the "published_cover_asset_id" field.
func (u *ImageCreationTemplateUpsert) ClearPublishedCoverAssetID() *ImageCreationTemplateUpsert {
	u.SetNull(imagecreationtemplate.FieldPublishedCoverAssetID)
	return u
}

// SetHomePosition sets the "home_position" field.
func (u *ImageCreationTemplateUpsert) SetHomePosition(v int16) *ImageCreationTemplateUpsert {
	u.Set(imagecreationtemplate.FieldHomePosition, v)
	return u
}

// UpdateHomePosition sets the "home_position" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsert) UpdateHomePosition() *ImageCreationTemplateUpsert {
	u.SetExcluded(imagecreationtemplate.FieldHomePosition)
	return u
}

// AddHomePosition adds v to the "home_position" field.
func (u *ImageCreationTemplateUpsert) AddHomePosition(v int16) *ImageCreationTemplateUpsert {
	u.Add(imagecreationtemplate.FieldHomePosition, v)
	return u
}

// ClearHomePosition clears the value of the "home_position" field.
func (u *ImageCreationTemplateUpsert) ClearHomePosition() *ImageCreationTemplateUpsert {
	u.SetNull(imagecreationtemplate.FieldHomePosition)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *ImageCreationTemplateUpsert) SetCreatedBy(v int64) *ImageCreationTemplateUpsert {
	u.Set(imagecreationtemplate.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsert) UpdateCreatedBy() *ImageCreationTemplateUpsert {
	u.SetExcluded(imagecreationtemplate.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ImageCreationTemplateUpsert) SetUpdatedBy(v int64) *ImageCreationTemplateUpsert {
	u.Set(imagecreationtemplate.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsert) UpdateUpdatedBy() *ImageCreationTemplateUpsert {
	u.SetExcluded(imagecreationtemplate.FieldUpdatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageCreationTemplateUpsert) SetUpdatedAt(v time.Time) *ImageCreationTemplateUpsert {
	u.Set(imagecreationtemplate.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsert) UpdateUpdatedAt() *ImageCreationTemplateUpsert {
	u.SetExcluded(imagecreationtemplate.FieldUpdatedAt)
	return u
}

// SetPublishedAt sets the "published_at" field.
func (u *ImageCreationTemplateUpsert) SetPublishedAt(v time.Time) *ImageCreationTemplateUpsert {
	u.Set(imagecreationtemplate.FieldPublishedAt, v)
	return u
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsert) UpdatePublishedAt() *ImageCreationTemplateUpsert {
	u.SetExcluded(imagecreationtemplate.FieldPublishedAt)
	return u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *ImageCreationTemplateUpsert) ClearPublishedAt() *ImageCreationTemplateUpsert {
	u.SetNull(imagecreationtemplate.FieldPublishedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ImageCreationTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageCreationTemplateUpsertOne) UpdateNewValues() *ImageCreationTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(imagecreationtemplate.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageCreationTemplate.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ImageCreationTemplateUpsertOne) Ignore() *ImageCreationTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageCreationTemplateUpsertOne) DoNothing() *ImageCreationTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageCreationTemplateCreate.OnConflict
// documentation for more info.
func (u *ImageCreationTemplateUpsertOne) Update(set func(*ImageCreationTemplateUpsert)) *ImageCreationTemplateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageCreationTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetState sets the "state" field.
func (u *ImageCreationTemplateUpsertOne) SetState(v string) *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertOne) UpdateState() *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdateState()
	})
}

// SetDraftData sets the "draft_data" field.
func (u *ImageCreationTemplateUpsertOne) SetDraftData(v domain.ImageCreationTemplateDocument) *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetDraftData(v)
	})
}

// UpdateDraftData sets the "draft_data" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertOne) UpdateDraftData() *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdateDraftData()
	})
}

// SetPublishedData sets the "published_data" field.
func (u *ImageCreationTemplateUpsertOne) SetPublishedData(v *domain.ImageCreationTemplateDocument) *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetPublishedData(v)
	})
}

// UpdatePublishedData sets the "published_data" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertOne) UpdatePublishedData() *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdatePublishedData()
	})
}

// ClearPublishedData clears the value of the "published_data" field.
func (u *ImageCreationTemplateUpsertOne) ClearPublishedData() *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.ClearPublishedData()
	})
}

// SetRevision sets the "revision" field.
func (u *ImageCreationTemplateUpsertOne) SetRevision(v int) *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *ImageCreationTemplateUpsertOne) AddRevision(v int) *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertOne) UpdateRevision() *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdateRevision()
	})
}

// SetPublishedVersion sets the "published_version" field.
func (u *ImageCreationTemplateUpsertOne) SetPublishedVersion(v int) *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetPublishedVersion(v)
	})
}

// AddPublishedVersion adds v to the "published_version" field.
func (u *ImageCreationTemplateUpsertOne) AddPublishedVersion(v int) *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.AddPublishedVersion(v)
	})
}

// UpdatePublishedVersion sets the "published_version" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertOne) UpdatePublishedVersion() *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdatePublishedVersion()
	})
}

// SetDraftCoverAssetID sets the "draft_cover_asset_id" field.
func (u *ImageCreationTemplateUpsertOne) SetDraftCoverAssetID(v string) *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetDraftCoverAssetID(v)
	})
}

// UpdateDraftCoverAssetID sets the "draft_cover_asset_id" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertOne) UpdateDraftCoverAssetID() *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdateDraftCoverAssetID()
	})
}

// ClearDraftCoverAssetID clears the value of the "draft_cover_asset_id" field.
func (u *ImageCreationTemplateUpsertOne) ClearDraftCoverAssetID() *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.ClearDraftCoverAssetID()
	})
}

// SetPublishedCoverAssetID sets the "published_cover_asset_id" field.
func (u *ImageCreationTemplateUpsertOne) SetPublishedCoverAssetID(v string) *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetPublishedCoverAssetID(v)
	})
}

// UpdatePublishedCoverAssetID sets the "published_cover_asset_id" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertOne) UpdatePublishedCoverAssetID() *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdatePublishedCoverAssetID()
	})
}

// ClearPublishedCoverAssetID clears the value of the "published_cover_asset_id" field.
func (u *ImageCreationTemplateUpsertOne) ClearPublishedCoverAssetID() *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.ClearPublishedCoverAssetID()
	})
}

// SetHomePosition sets the "home_position" field.
func (u *ImageCreationTemplateUpsertOne) SetHomePosition(v int16) *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetHomePosition(v)
	})
}

// AddHomePosition adds v to the "home_position" field.
func (u *ImageCreationTemplateUpsertOne) AddHomePosition(v int16) *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.AddHomePosition(v)
	})
}

// UpdateHomePosition sets the "home_position" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertOne) UpdateHomePosition() *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdateHomePosition()
	})
}

// ClearHomePosition clears the value of the "home_position" field.
func (u *ImageCreationTemplateUpsertOne) ClearHomePosition() *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.ClearHomePosition()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ImageCreationTemplateUpsertOne) SetCreatedBy(v int64) *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertOne) UpdateCreatedBy() *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ImageCreationTemplateUpsertOne) SetUpdatedBy(v int64) *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertOne) UpdateUpdatedBy() *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdateUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageCreationTemplateUpsertOne) SetUpdatedAt(v time.Time) *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertOne) UpdateUpdatedAt() *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *ImageCreationTemplateUpsertOne) SetPublishedAt(v time.Time) *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertOne) UpdatePublishedAt() *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *ImageCreationTemplateUpsertOne) ClearPublishedAt() *ImageCreationTemplateUpsertOne {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.ClearPublishedAt()
	})
}

// Exec executes the query.
func (u *ImageCreationTemplateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageCreationTemplateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageCreationTemplateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ImageCreationTemplateUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ImageCreationTemplateUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ImageCreationTemplateCreateBulk is the builder for creating many ImageCreationTemplate entities in bulk.
type ImageCreationTemplateCreateBulk struct {
	config
	err      error
	builders []*ImageCreationTemplateCreate
	conflict []sql.ConflictOption
}

// Save creates the ImageCreationTemplate entities in the database.
func (_c *ImageCreationTemplateCreateBulk) Save(ctx context.Context) ([]*ImageCreationTemplate, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ImageCreationTemplate, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ImageCreationTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ImageCreationTemplateCreateBulk) SaveX(ctx context.Context) []*ImageCreationTemplate {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ImageCreationTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ImageCreationTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ImageCreationTemplate.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ImageCreationTemplateUpsert) {
//			SetState(v+v).
//		}).
//		Exec(ctx)
func (_c *ImageCreationTemplateCreateBulk) OnConflict(opts ...sql.ConflictOption) *ImageCreationTemplateUpsertBulk {
	_c.conflict = opts
	return &ImageCreationTemplateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ImageCreationTemplate.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ImageCreationTemplateCreateBulk) OnConflictColumns(columns ...string) *ImageCreationTemplateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ImageCreationTemplateUpsertBulk{
		create: _c,
	}
}

// ImageCreationTemplateUpsertBulk is the builder for "upsert"-ing
// a bulk of ImageCreationTemplate nodes.
type ImageCreationTemplateUpsertBulk struct {
	create *ImageCreationTemplateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ImageCreationTemplate.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ImageCreationTemplateUpsertBulk) UpdateNewValues() *ImageCreationTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(imagecreationtemplate.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ImageCreationTemplate.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ImageCreationTemplateUpsertBulk) Ignore() *ImageCreationTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ImageCreationTemplateUpsertBulk) DoNothing() *ImageCreationTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ImageCreationTemplateCreateBulk.OnConflict
// documentation for more info.
func (u *ImageCreationTemplateUpsertBulk) Update(set func(*ImageCreationTemplateUpsert)) *ImageCreationTemplateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ImageCreationTemplateUpsert{UpdateSet: update})
	}))
	return u
}

// SetState sets the "state" field.
func (u *ImageCreationTemplateUpsertBulk) SetState(v string) *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetState(v)
	})
}

// UpdateState sets the "state" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertBulk) UpdateState() *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdateState()
	})
}

// SetDraftData sets the "draft_data" field.
func (u *ImageCreationTemplateUpsertBulk) SetDraftData(v domain.ImageCreationTemplateDocument) *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetDraftData(v)
	})
}

// UpdateDraftData sets the "draft_data" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertBulk) UpdateDraftData() *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdateDraftData()
	})
}

// SetPublishedData sets the "published_data" field.
func (u *ImageCreationTemplateUpsertBulk) SetPublishedData(v *domain.ImageCreationTemplateDocument) *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetPublishedData(v)
	})
}

// UpdatePublishedData sets the "published_data" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertBulk) UpdatePublishedData() *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdatePublishedData()
	})
}

// ClearPublishedData clears the value of the "published_data" field.
func (u *ImageCreationTemplateUpsertBulk) ClearPublishedData() *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.ClearPublishedData()
	})
}

// SetRevision sets the "revision" field.
func (u *ImageCreationTemplateUpsertBulk) SetRevision(v int) *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *ImageCreationTemplateUpsertBulk) AddRevision(v int) *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertBulk) UpdateRevision() *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdateRevision()
	})
}

// SetPublishedVersion sets the "published_version" field.
func (u *ImageCreationTemplateUpsertBulk) SetPublishedVersion(v int) *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetPublishedVersion(v)
	})
}

// AddPublishedVersion adds v to the "published_version" field.
func (u *ImageCreationTemplateUpsertBulk) AddPublishedVersion(v int) *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.AddPublishedVersion(v)
	})
}

// UpdatePublishedVersion sets the "published_version" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertBulk) UpdatePublishedVersion() *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdatePublishedVersion()
	})
}

// SetDraftCoverAssetID sets the "draft_cover_asset_id" field.
func (u *ImageCreationTemplateUpsertBulk) SetDraftCoverAssetID(v string) *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetDraftCoverAssetID(v)
	})
}

// UpdateDraftCoverAssetID sets the "draft_cover_asset_id" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertBulk) UpdateDraftCoverAssetID() *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdateDraftCoverAssetID()
	})
}

// ClearDraftCoverAssetID clears the value of the "draft_cover_asset_id" field.
func (u *ImageCreationTemplateUpsertBulk) ClearDraftCoverAssetID() *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.ClearDraftCoverAssetID()
	})
}

// SetPublishedCoverAssetID sets the "published_cover_asset_id" field.
func (u *ImageCreationTemplateUpsertBulk) SetPublishedCoverAssetID(v string) *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetPublishedCoverAssetID(v)
	})
}

// UpdatePublishedCoverAssetID sets the "published_cover_asset_id" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertBulk) UpdatePublishedCoverAssetID() *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdatePublishedCoverAssetID()
	})
}

// ClearPublishedCoverAssetID clears the value of the "published_cover_asset_id" field.
func (u *ImageCreationTemplateUpsertBulk) ClearPublishedCoverAssetID() *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.ClearPublishedCoverAssetID()
	})
}

// SetHomePosition sets the "home_position" field.
func (u *ImageCreationTemplateUpsertBulk) SetHomePosition(v int16) *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetHomePosition(v)
	})
}

// AddHomePosition adds v to the "home_position" field.
func (u *ImageCreationTemplateUpsertBulk) AddHomePosition(v int16) *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.AddHomePosition(v)
	})
}

// UpdateHomePosition sets the "home_position" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertBulk) UpdateHomePosition() *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdateHomePosition()
	})
}

// ClearHomePosition clears the value of the "home_position" field.
func (u *ImageCreationTemplateUpsertBulk) ClearHomePosition() *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.ClearHomePosition()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *ImageCreationTemplateUpsertBulk) SetCreatedBy(v int64) *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertBulk) UpdateCreatedBy() *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdateCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ImageCreationTemplateUpsertBulk) SetUpdatedBy(v int64) *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertBulk) UpdateUpdatedBy() *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdateUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ImageCreationTemplateUpsertBulk) SetUpdatedAt(v time.Time) *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertBulk) UpdateUpdatedAt() *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *ImageCreationTemplateUpsertBulk) SetPublishedAt(v time.Time) *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *ImageCreationTemplateUpsertBulk) UpdatePublishedAt() *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *ImageCreationTemplateUpsertBulk) ClearPublishedAt() *ImageCreationTemplateUpsertBulk {
	return u.Update(func(s *ImageCreationTemplateUpsert) {
		s.ClearPublishedAt()
	})
}

// Exec executes the query.
func (u *ImageCreationTemplateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ImageCreationTemplateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ImageCreationTemplateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ImageCreationTemplateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
