// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/imagecreationasset"
	"github.com/Wei-Shaw/sub2api/ent/imagecreationtemplate"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ImageCreationAssetUpdate is the builder for updating ImageCreationAsset entities.
type ImageCreationAssetUpdate struct {
	config
	hooks    []Hook
	mutation *ImageCreationAssetMutation
}

// Where appends a list predicates to the ImageCreationAssetUpdate builder.
func (_u *ImageCreationAssetUpdate) Where(ps ...predicate.ImageCreationAsset) *ImageCreationAssetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetContent sets the "content" field.
func (_u *ImageCreationAssetUpdate) SetContent(v []byte) *ImageCreationAssetUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *ImageCreationAssetUpdate) SetContentType(v string) *ImageCreationAssetUpdate {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *ImageCreationAssetUpdate) SetNillableContentType(v *string) *ImageCreationAssetUpdate {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetByteSize sets the "byte_size" field.
func (_u *ImageCreationAssetUpdate) SetByteSize(v int) *ImageCreationAssetUpdate {
	_u.mutation.ResetByteSize()
	_u.mutation.SetByteSize(v)
	return _u
}

// SetNillableByteSize sets the "byte_size" field if the given value is not nil.
func (_u *ImageCreationAssetUpdate) SetNillableByteSize(v *int) *ImageCreationAssetUpdate {
	if v != nil {
		_u.SetByteSize(*v)
	}
	return _u
}

// AddByteSize adds value to the "byte_size" field.
func (_u *ImageCreationAssetUpdate) AddByteSize(v int) *ImageCreationAssetUpdate {
	_u.mutation.AddByteSize(v)
	return _u
}

// SetWidth sets the "width" field.
func (_u *ImageCreationAssetUpdate) SetWidth(v int) *ImageCreationAssetUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *ImageCreationAssetUpdate) SetNillableWidth(v *int) *ImageCreationAssetUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *ImageCreationAssetUpdate) AddWidth(v int) *ImageCreationAssetUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *ImageCreationAssetUpdate) SetHeight(v int) *ImageCreationAssetUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *ImageCreationAssetUpdate) SetNillableHeight(v *int) *ImageCreationAssetUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *ImageCreationAssetUpdate) AddHeight(v int) *ImageCreationAssetUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *ImageCreationAssetUpdate) SetSourceType(v string) *ImageCreationAssetUpdate {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *ImageCreationAssetUpdate) SetNillableSourceType(v *string) *ImageCreationAssetUpdate {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceProvider sets the "source_provider" field.
func (_u *ImageCreationAssetUpdate) SetSourceProvider(v string) *ImageCreationAssetUpdate {
	_u.mutation.SetSourceProvider(v)
	return _u
}

// SetNillableSourceProvider sets the "source_provider" field if the given value is not nil.
func (_u *ImageCreationAssetUpdate) SetNillableSourceProvider(v *string) *ImageCreationAssetUpdate {
	if v != nil {
		_u.SetSourceProvider(*v)
	}
	return _u
}

// ClearSourceProvider clears the value of the "source_provider" field.
func (_u *ImageCreationAssetUpdate) ClearSourceProvider() *ImageCreationAssetUpdate {
	_u.mutation.ClearSourceProvider()
	return _u
}

// SetSourceModel sets the "source_model" field.
func (_u *ImageCreationAssetUpdate) SetSourceModel(v string) *ImageCreationAssetUpdate {
	_u.mutation.SetSourceModel(v)
	return _u
}

// SetNillableSourceModel sets the "source_model" field if the given value is not nil.
func (_u *ImageCreationAssetUpdate) SetNillableSourceModel(v *string) *ImageCreationAssetUpdate {
	if v != nil {
		_u.SetSourceModel(*v)
	}
	return _u
}

// ClearSourceModel clears the value of the "source_model" field.
func (_u *ImageCreationAssetUpdate) ClearSourceModel() *ImageCreationAssetUpdate {
	_u.mutation.ClearSourceModel()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ImageCreationAssetUpdate) SetCreatedBy(v int64) *ImageCreationAssetUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ImageCreationAssetUpdate) SetNillableCreatedBy(v *int64) *ImageCreationAssetUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *ImageCreationAssetUpdate) SetCreatorID(id int64) *ImageCreationAssetUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *ImageCreationAssetUpdate) SetCreator(v *User) *ImageCreationAssetUpdate {
	return _u.SetCreatorID(v.ID)
}

// AddDraftTemplateIDs adds the "draft_templates" edge to the ImageCreationTemplate entity by IDs.
func (_u *ImageCreationAssetUpdate) AddDraftTemplateIDs(ids ...int64) *ImageCreationAssetUpdate {
	_u.mutation.AddDraftTemplateIDs(ids...)
	return _u
}

// AddDraftTemplates adds the "draft_templates" edges to the ImageCreationTemplate entity.
func (_u *ImageCreationAssetUpdate) AddDraftTemplates(v ...*ImageCreationTemplate) *ImageCreationAssetUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDraftTemplateIDs(ids...)
}

// AddPublishedTemplateIDs adds the "published_templates" edge to the ImageCreationTemplate entity by IDs.
func (_u *ImageCreationAssetUpdate) AddPublishedTemplateIDs(ids ...int64) *ImageCreationAssetUpdate {
	_u.mutation.AddPublishedTemplateIDs(ids...)
	return _u
}

// AddPublishedTemplates adds the "published_templates" edges to the ImageCreationTemplate entity.
func (_u *ImageCreationAssetUpdate) AddPublishedTemplates(v ...*ImageCreationTemplate) *ImageCreationAssetUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPublishedTemplateIDs(ids...)
}

// Mutation returns the ImageCreationAssetMutation object of the builder.
func (_u *ImageCreationAssetUpdate) Mutation() *ImageCreationAssetMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *ImageCreationAssetUpdate) ClearCreator() *ImageCreationAssetUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// ClearDraftTemplates clears all "draft_templates" edges to the ImageCreationTemplate entity.
func (_u *ImageCreationAssetUpdate) ClearDraftTemplates() *ImageCreationAssetUpdate {
	_u.mutation.ClearDraftTemplates()
	return _u
}

// RemoveDraftTemplateIDs removes the "draft_templates" edge to ImageCreationTemplate entities by IDs.
func (_u *ImageCreationAssetUpdate) RemoveDraftTemplateIDs(ids ...int64) *ImageCreationAssetUpdate {
	_u.mutation.RemoveDraftTemplateIDs(ids...)
	return _u
}

// RemoveDraftTemplates removes "draft_templates" edges to ImageCreationTemplate entities.
func (_u *ImageCreationAssetUpdate) RemoveDraftTemplates(v ...*ImageCreationTemplate) *ImageCreationAssetUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDraftTemplateIDs(ids...)
}

// ClearPublishedTemplates clears all "published_templates" edges to the ImageCreationTemplate entity.
func (_u *ImageCreationAssetUpdate) ClearPublishedTemplates() *ImageCreationAssetUpdate {
	_u.mutation.ClearPublishedTemplates()
	return _u
}

// RemovePublishedTemplateIDs removes the "published_templates" edge to ImageCreationTemplate entities by IDs.
func (_u *ImageCreationAssetUpdate) RemovePublishedTemplateIDs(ids ...int64) *ImageCreationAssetUpdate {
	_u.mutation.RemovePublishedTemplateIDs(ids...)
	return _u
}

// RemovePublishedTemplates removes "published_templates" edges to ImageCreationTemplate entities.
func (_u *ImageCreationAssetUpdate) RemovePublishedTemplates(v ...*ImageCreationTemplate) *ImageCreationAssetUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePublishedTemplateIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImageCreationAssetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageCreationAssetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImageCreationAssetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageCreationAssetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageCreationAssetUpdate) check() error {
	if v, ok := _u.mutation.ContentType(); ok {
		if err := imagecreationasset.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ByteSize(); ok {
		if err := imagecreationasset.ByteSizeValidator(v); err != nil {
			return &ValidationError{Name: "byte_size", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.byte_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Width(); ok {
		if err := imagecreationasset.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.width": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Height(); ok {
		if err := imagecreationasset.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.height": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := imagecreationasset.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceProvider(); ok {
		if err := imagecreationasset.SourceProviderValidator(v); err != nil {
			return &ValidationError{Name: "source_provider", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.source_provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceModel(); ok {
		if err := imagecreationasset.SourceModelValidator(v); err != nil {
			return &ValidationError{Name: "source_model", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.source_model": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ImageCreationAsset.creator"`)
	}
	return nil
}

func (_u *ImageCreationAssetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imagecreationasset.Table, imagecreationasset.Columns, sqlgraph.NewFieldSpec(imagecreationasset.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(imagecreationasset.FieldContent, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(imagecreationasset.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ByteSize(); ok {
		_spec.SetField(imagecreationasset.FieldByteSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedByteSize(); ok {
		_spec.AddField(imagecreationasset.FieldByteSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(imagecreationasset.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(imagecreationasset.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(imagecreationasset.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(imagecreationasset.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(imagecreationasset.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceProvider(); ok {
		_spec.SetField(imagecreationasset.FieldSourceProvider, field.TypeString, value)
	}
	if _u.mutation.SourceProviderCleared() {
		_spec.ClearField(imagecreationasset.FieldSourceProvider, field.TypeString)
	}
	if value, ok := _u.mutation.SourceModel(); ok {
		_spec.SetField(imagecreationasset.FieldSourceModel, field.TypeString, value)
	}
	if _u.mutation.SourceModelCleared() {
		_spec.ClearField(imagecreationasset.FieldSourceModel, field.TypeString)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationasset.CreatorTable,
			Columns: []string{imagecreationasset.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationasset.CreatorTable,
			Columns: []string{imagecreationasset.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DraftTemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imagecreationasset.DraftTemplatesTable,
			Columns: []string{imagecreationasset.DraftTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationtemplate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDraftTemplatesIDs(); len(nodes) > 0 && !_u.mutation.DraftTemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imagecreationasset.DraftTemplatesTable,
			Columns: []string{imagecreationasset.DraftTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationtemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DraftTemplatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imagecreationasset.DraftTemplatesTable,
			Columns: []string{imagecreationasset.DraftTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationtemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PublishedTemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imagecreationasset.PublishedTemplatesTable,
			Columns: []string{imagecreationasset.PublishedTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationtemplate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPublishedTemplatesIDs(); len(nodes) > 0 && !_u.mutation.PublishedTemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imagecreationasset.PublishedTemplatesTable,
			Columns: []string{imagecreationasset.PublishedTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationtemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PublishedTemplatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imagecreationasset.PublishedTemplatesTable,
			Columns: []string{imagecreationasset.PublishedTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationtemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imagecreationasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImageCreationAssetUpdateOne is the builder for updating a single ImageCreationAsset entity.
type ImageCreationAssetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageCreationAssetMutation
}

// SetContent sets the "content" field.
func (_u *ImageCreationAssetUpdateOne) SetContent(v []byte) *ImageCreationAssetUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetContentType sets the "content_type" field.
func (_u *ImageCreationAssetUpdateOne) SetContentType(v string) *ImageCreationAssetUpdateOne {
	_u.mutation.SetContentType(v)
	return _u
}

// SetNillableContentType sets the "content_type" field if the given value is not nil.
func (_u *ImageCreationAssetUpdateOne) SetNillableContentType(v *string) *ImageCreationAssetUpdateOne {
	if v != nil {
		_u.SetContentType(*v)
	}
	return _u
}

// SetByteSize sets the "byte_size" field.
func (_u *ImageCreationAssetUpdateOne) SetByteSize(v int) *ImageCreationAssetUpdateOne {
	_u.mutation.ResetByteSize()
	_u.mutation.SetByteSize(v)
	return _u
}

// SetNillableByteSize sets the "byte_size" field if the given value is not nil.
func (_u *ImageCreationAssetUpdateOne) SetNillableByteSize(v *int) *ImageCreationAssetUpdateOne {
	if v != nil {
		_u.SetByteSize(*v)
	}
	return _u
}

// AddByteSize adds value to the "byte_size" field.
func (_u *ImageCreationAssetUpdateOne) AddByteSize(v int) *ImageCreationAssetUpdateOne {
	_u.mutation.AddByteSize(v)
	return _u
}

// SetWidth sets the "width" field.
func (_u *ImageCreationAssetUpdateOne) SetWidth(v int) *ImageCreationAssetUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *ImageCreationAssetUpdateOne) SetNillableWidth(v *int) *ImageCreationAssetUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *ImageCreationAssetUpdateOne) AddWidth(v int) *ImageCreationAssetUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *ImageCreationAssetUpdateOne) SetHeight(v int) *ImageCreationAssetUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *ImageCreationAssetUpdateOne) SetNillableHeight(v *int) *ImageCreationAssetUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *ImageCreationAssetUpdateOne) AddHeight(v int) *ImageCreationAssetUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// SetSourceType sets the "source_type" field.
func (_u *ImageCreationAssetUpdateOne) SetSourceType(v string) *ImageCreationAssetUpdateOne {
	_u.mutation.SetSourceType(v)
	return _u
}

// SetNillableSourceType sets the "source_type" field if the given value is not nil.
func (_u *ImageCreationAssetUpdateOne) SetNillableSourceType(v *string) *ImageCreationAssetUpdateOne {
	if v != nil {
		_u.SetSourceType(*v)
	}
	return _u
}

// SetSourceProvider sets the "source_provider" field.
func (_u *ImageCreationAssetUpdateOne) SetSourceProvider(v string) *ImageCreationAssetUpdateOne {
	_u.mutation.SetSourceProvider(v)
	return _u
}

// SetNillableSourceProvider sets the "source_provider" field if the given value is not nil.
func (_u *ImageCreationAssetUpdateOne) SetNillableSourceProvider(v *string) *ImageCreationAssetUpdateOne {
	if v != nil {
		_u.SetSourceProvider(*v)
	}
	return _u
}

// ClearSourceProvider clears the value of the "source_provider" field.
func (_u *ImageCreationAssetUpdateOne) ClearSourceProvider() *ImageCreationAssetUpdateOne {
	_u.mutation.ClearSourceProvider()
	return _u
}

// SetSourceModel sets the "source_model" field.
func (_u *ImageCreationAssetUpdateOne) SetSourceModel(v string) *ImageCreationAssetUpdateOne {
	_u.mutation.SetSourceModel(v)
	return _u
}

// SetNillableSourceModel sets the "source_model" field if the given value is not nil.
func (_u *ImageCreationAssetUpdateOne) SetNillableSourceModel(v *string) *ImageCreationAssetUpdateOne {
	if v != nil {
		_u.SetSourceModel(*v)
	}
	return _u
}

// ClearSourceModel clears the value of the "source_model" field.
func (_u *ImageCreationAssetUpdateOne) ClearSourceModel() *ImageCreationAssetUpdateOne {
	_u.mutation.ClearSourceModel()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ImageCreationAssetUpdateOne) SetCreatedBy(v int64) *ImageCreationAssetUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ImageCreationAssetUpdateOne) SetNillableCreatedBy(v *int64) *ImageCreationAssetUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *ImageCreationAssetUpdateOne) SetCreatorID(id int64) *ImageCreationAssetUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *ImageCreationAssetUpdateOne) SetCreator(v *User) *ImageCreationAssetUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// AddDraftTemplateIDs adds the "draft_templates" edge to the ImageCreationTemplate entity by IDs.
func (_u *ImageCreationAssetUpdateOne) AddDraftTemplateIDs(ids ...int64) *ImageCreationAssetUpdateOne {
	_u.mutation.AddDraftTemplateIDs(ids...)
	return _u
}

// AddDraftTemplates adds the "draft_templates" edges to the ImageCreationTemplate entity.
func (_u *ImageCreationAssetUpdateOne) AddDraftTemplates(v ...*ImageCreationTemplate) *ImageCreationAssetUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDraftTemplateIDs(ids...)
}

// AddPublishedTemplateIDs adds the "published_templates" edge to the ImageCreationTemplate entity by IDs.
func (_u *ImageCreationAssetUpdateOne) AddPublishedTemplateIDs(ids ...int64) *ImageCreationAssetUpdateOne {
	_u.mutation.AddPublishedTemplateIDs(ids...)
	return _u
}

// AddPublishedTemplates adds the "published_templates" edges to the ImageCreationTemplate entity.
func (_u *ImageCreationAssetUpdateOne) AddPublishedTemplates(v ...*ImageCreationTemplate) *ImageCreationAssetUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPublishedTemplateIDs(ids...)
}

// Mutation returns the ImageCreationAssetMutation object of the builder.
func (_u *ImageCreationAssetUpdateOne) Mutation() *ImageCreationAssetMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *ImageCreationAssetUpdateOne) ClearCreator() *ImageCreationAssetUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// ClearDraftTemplates clears all "draft_templates" edges to the ImageCreationTemplate entity.
func (_u *ImageCreationAssetUpdateOne) ClearDraftTemplates() *ImageCreationAssetUpdateOne {
	_u.mutation.ClearDraftTemplates()
	return _u
}

// RemoveDraftTemplateIDs removes the "draft_templates" edge to ImageCreationTemplate entities by IDs.
func (_u *ImageCreationAssetUpdateOne) RemoveDraftTemplateIDs(ids ...int64) *ImageCreationAssetUpdateOne {
	_u.mutation.RemoveDraftTemplateIDs(ids...)
	return _u
}

// RemoveDraftTemplates removes "draft_templates" edges to ImageCreationTemplate entities.
func (_u *ImageCreationAssetUpdateOne) RemoveDraftTemplates(v ...*ImageCreationTemplate) *ImageCreationAssetUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDraftTemplateIDs(ids...)
}

// ClearPublishedTemplates clears all "published_templates" edges to the ImageCreationTemplate entity.
func (_u *ImageCreationAssetUpdateOne) ClearPublishedTemplates() *ImageCreationAssetUpdateOne {
	_u.mutation.ClearPublishedTemplates()
	return _u
}

// RemovePublishedTemplateIDs removes the "published_templates" edge to ImageCreationTemplate entities by IDs.
func (_u *ImageCreationAssetUpdateOne) RemovePublishedTemplateIDs(ids ...int64) *ImageCreationAssetUpdateOne {
	_u.mutation.RemovePublishedTemplateIDs(ids...)
	return _u
}

// RemovePublishedTemplates removes "published_templates" edges to ImageCreationTemplate entities.
func (_u *ImageCreationAssetUpdateOne) RemovePublishedTemplates(v ...*ImageCreationTemplate) *ImageCreationAssetUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePublishedTemplateIDs(ids...)
}

// Where appends a list predicates to the ImageCreationAssetUpdate builder.
func (_u *ImageCreationAssetUpdateOne) Where(ps ...predicate.ImageCreationAsset) *ImageCreationAssetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImageCreationAssetUpdateOne) Select(field string, fields ...string) *ImageCreationAssetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ImageCreationAsset entity.
func (_u *ImageCreationAssetUpdateOne) Save(ctx context.Context) (*ImageCreationAsset, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageCreationAssetUpdateOne) SaveX(ctx context.Context) *ImageCreationAsset {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImageCreationAssetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageCreationAssetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageCreationAssetUpdateOne) check() error {
	if v, ok := _u.mutation.ContentType(); ok {
		if err := imagecreationasset.ContentTypeValidator(v); err != nil {
			return &ValidationError{Name: "content_type", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.content_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ByteSize(); ok {
		if err := imagecreationasset.ByteSizeValidator(v); err != nil {
			return &ValidationError{Name: "byte_size", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.byte_size": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Width(); ok {
		if err := imagecreationasset.WidthValidator(v); err != nil {
			return &ValidationError{Name: "width", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.width": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Height(); ok {
		if err := imagecreationasset.HeightValidator(v); err != nil {
			return &ValidationError{Name: "height", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.height": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceType(); ok {
		if err := imagecreationasset.SourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "source_type", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.source_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceProvider(); ok {
		if err := imagecreationasset.SourceProviderValidator(v); err != nil {
			return &ValidationError{Name: "source_provider", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.source_provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SourceModel(); ok {
		if err := imagecreationasset.SourceModelValidator(v); err != nil {
			return &ValidationError{Name: "source_model", err: fmt.Errorf(`ent: validator failed for field "ImageCreationAsset.source_model": %w`, err)}
		}
	}
	if _u.mutation.CreatorCleared() && len(_u.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ImageCreationAsset.creator"`)
	}
	return nil
}

func (_u *ImageCreationAssetUpdateOne) sqlSave(ctx context.Context) (_node *ImageCreationAsset, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(imagecreationasset.Table, imagecreationasset.Columns, sqlgraph.NewFieldSpec(imagecreationasset.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ImageCreationAsset.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, imagecreationasset.FieldID)
		for _, f := range fields {
			if !imagecreationasset.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != imagecreationasset.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(imagecreationasset.FieldContent, field.TypeBytes, value)
	}
	if value, ok := _u.mutation.ContentType(); ok {
		_spec.SetField(imagecreationasset.FieldContentType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ByteSize(); ok {
		_spec.SetField(imagecreationasset.FieldByteSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedByteSize(); ok {
		_spec.AddField(imagecreationasset.FieldByteSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(imagecreationasset.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(imagecreationasset.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(imagecreationasset.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(imagecreationasset.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SourceType(); ok {
		_spec.SetField(imagecreationasset.FieldSourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceProvider(); ok {
		_spec.SetField(imagecreationasset.FieldSourceProvider, field.TypeString, value)
	}
	if _u.mutation.SourceProviderCleared() {
		_spec.ClearField(imagecreationasset.FieldSourceProvider, field.TypeString)
	}
	if value, ok := _u.mutation.SourceModel(); ok {
		_spec.SetField(imagecreationasset.FieldSourceModel, field.TypeString, value)
	}
	if _u.mutation.SourceModelCleared() {
		_spec.ClearField(imagecreationasset.FieldSourceModel, field.TypeString)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationasset.CreatorTable,
			Columns: []string{imagecreationasset.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   imagecreationasset.CreatorTable,
			Columns: []string{imagecreationasset.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DraftTemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imagecreationasset.DraftTemplatesTable,
			Columns: []string{imagecreationasset.DraftTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationtemplate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDraftTemplatesIDs(); len(nodes) > 0 && !_u.mutation.DraftTemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imagecreationasset.DraftTemplatesTable,
			Columns: []string{imagecreationasset.DraftTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationtemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DraftTemplatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imagecreationasset.DraftTemplatesTable,
			Columns: []string{imagecreationasset.DraftTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationtemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PublishedTemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imagecreationasset.PublishedTemplatesTable,
			Columns: []string{imagecreationasset.PublishedTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationtemplate.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPublishedTemplatesIDs(); len(nodes) > 0 && !_u.mutation.PublishedTemplatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imagecreationasset.PublishedTemplatesTable,
			Columns: []string{imagecreationasset.PublishedTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationtemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PublishedTemplatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   imagecreationasset.PublishedTemplatesTable,
			Columns: []string{imagecreationasset.PublishedTemplatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(imagecreationtemplate.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ImageCreationAsset{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{imagecreationasset.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
