// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/imagecreationasset"
	"github.com/Wei-Shaw/sub2api/ent/imagecreationtemplate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// ImageCreationTemplate is the model entity for the ImageCreationTemplate schema.
type ImageCreationTemplate struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// State holds the value of the "state" field.
	State string `json:"state,omitempty"`
	// DraftData holds the value of the "draft_data" field.
	DraftData domain.ImageCreationTemplateDocument `json:"draft_data,omitempty"`
	// PublishedData holds the value of the "published_data" field.
	PublishedData *domain.ImageCreationTemplateDocument `json:"published_data,omitempty"`
	// Revision holds the value of the "revision" field.
	Revision int `json:"revision,omitempty"`
	// PublishedVersion holds the value of the "published_version" field.
	PublishedVersion int `json:"published_version,omitempty"`
	// DraftCoverAssetID holds the value of the "draft_cover_asset_id" field.
	DraftCoverAssetID *string `json:"draft_cover_asset_id,omitempty"`
	// PublishedCoverAssetID holds the value of the "published_cover_asset_id" field.
	PublishedCoverAssetID *string `json:"published_cover_asset_id,omitempty"`
	// HomePosition holds the value of the "home_position" field.
	HomePosition *int16 `json:"home_position,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy int64 `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy int64 `json:"updated_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ImageCreationTemplateQuery when eager-loading is set.
	Edges        ImageCreationTemplateEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ImageCreationTemplateEdges holds the relations/edges for other nodes in the graph.
type ImageCreationTemplateEdges struct {
	// DraftCover holds the value of the draft_cover edge.
	DraftCover *ImageCreationAsset `json:"draft_cover,omitempty"`
	// PublishedCover holds the value of the published_cover edge.
	PublishedCover *ImageCreationAsset `json:"published_cover,omitempty"`
	// Creator holds the value of the creator edge.
	Creator *User `json:"creator,omitempty"`
	// Updater holds the value of the updater edge.
	Updater *User `json:"updater,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// DraftCoverOrErr returns the DraftCover value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ImageCreationTemplateEdges) DraftCoverOrErr() (*ImageCreationAsset, error) {
	if e.DraftCover != nil {
		return e.DraftCover, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: imagecreationasset.Label}
	}
	return nil, &NotLoadedError{edge: "draft_cover"}
}

// PublishedCoverOrErr returns the PublishedCover value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ImageCreationTemplateEdges) PublishedCoverOrErr() (*ImageCreationAsset, error) {
	if e.PublishedCover != nil {
		return e.PublishedCover, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: imagecreationasset.Label}
	}
	return nil, &NotLoadedError{edge: "published_cover"}
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ImageCreationTemplateEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// UpdaterOrErr returns the Updater value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ImageCreationTemplateEdges) UpdaterOrErr() (*User, error) {
	if e.Updater != nil {
		return e.Updater, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "updater"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ImageCreationTemplate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case imagecreationtemplate.FieldDraftData, imagecreationtemplate.FieldPublishedData:
			values[i] = new([]byte)
		case imagecreationtemplate.FieldID, imagecreationtemplate.FieldRevision, imagecreationtemplate.FieldPublishedVersion, imagecreationtemplate.FieldHomePosition, imagecreationtemplate.FieldCreatedBy, imagecreationtemplate.FieldUpdatedBy:
			values[i] = new(sql.NullInt64)
		case imagecreationtemplate.FieldState, imagecreationtemplate.FieldDraftCoverAssetID, imagecreationtemplate.FieldPublishedCoverAssetID:
			values[i] = new(sql.NullString)
		case imagecreationtemplate.FieldCreatedAt, imagecreationtemplate.FieldUpdatedAt, imagecreationtemplate.FieldPublishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ImageCreationTemplate fields.
func (_m *ImageCreationTemplate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case imagecreationtemplate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case imagecreationtemplate.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				_m.State = value.String
			}
		case imagecreationtemplate.FieldDraftData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field draft_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DraftData); err != nil {
					return fmt.Errorf("unmarshal field draft_data: %w", err)
				}
			}
		case imagecreationtemplate.FieldPublishedData:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field published_data", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PublishedData); err != nil {
					return fmt.Errorf("unmarshal field published_data: %w", err)
				}
			}
		case imagecreationtemplate.FieldRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				_m.Revision = int(value.Int64)
			}
		case imagecreationtemplate.FieldPublishedVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field published_version", values[i])
			} else if value.Valid {
				_m.PublishedVersion = int(value.Int64)
			}
		case imagecreationtemplate.FieldDraftCoverAssetID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field draft_cover_asset_id", values[i])
			} else if value.Valid {
				_m.DraftCoverAssetID = new(string)
				*_m.DraftCoverAssetID = value.String
			}
		case imagecreationtemplate.FieldPublishedCoverAssetID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field published_cover_asset_id", values[i])
			} else if value.Valid {
				_m.PublishedCoverAssetID = new(string)
				*_m.PublishedCoverAssetID = value.String
			}
		case imagecreationtemplate.FieldHomePosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field home_position", values[i])
			} else if value.Valid {
				_m.HomePosition = new(int16)
				*_m.HomePosition = int16(value.Int64)
			}
		case imagecreationtemplate.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.Int64
			}
		case imagecreationtemplate.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.Int64
			}
		case imagecreationtemplate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case imagecreationtemplate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case imagecreationtemplate.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ImageCreationTemplate.
// This includes values selected through modifiers, order, etc.
func (_m *ImageCreationTemplate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryDraftCover queries the "draft_cover" edge of the ImageCreationTemplate entity.
func (_m *ImageCreationTemplate) QueryDraftCover() *ImageCreationAssetQuery {
	return NewImageCreationTemplateClient(_m.config).QueryDraftCover(_m)
}

// QueryPublishedCover queries the "published_cover" edge of the ImageCreationTemplate entity.
func (_m *ImageCreationTemplate) QueryPublishedCover() *ImageCreationAssetQuery {
	return NewImageCreationTemplateClient(_m.config).QueryPublishedCover(_m)
}

// QueryCreator queries the "creator" edge of the ImageCreationTemplate entity.
func (_m *ImageCreationTemplate) QueryCreator() *UserQuery {
	return NewImageCreationTemplateClient(_m.config).QueryCreator(_m)
}

// QueryUpdater queries the "updater" edge of the ImageCreationTemplate entity.
func (_m *ImageCreationTemplate) QueryUpdater() *UserQuery {
	return NewImageCreationTemplateClient(_m.config).QueryUpdater(_m)
}

// Update returns a builder for updating this ImageCreationTemplate.
// Note that you need to call ImageCreationTemplate.Unwrap() before calling this method if this ImageCreationTemplate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ImageCreationTemplate) Update() *ImageCreationTemplateUpdateOne {
	return NewImageCreationTemplateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ImageCreationTemplate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ImageCreationTemplate) Unwrap() *ImageCreationTemplate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ImageCreationTemplate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ImageCreationTemplate) String() string {
	var builder strings.Builder
	builder.WriteString("ImageCreationTemplate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("state=")
	builder.WriteString(_m.State)
	builder.WriteString(", ")
	builder.WriteString("draft_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.DraftData))
	builder.WriteString(", ")
	builder.WriteString("published_data=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublishedData))
	builder.WriteString(", ")
	builder.WriteString("revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revision))
	builder.WriteString(", ")
	builder.WriteString("published_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.PublishedVersion))
	builder.WriteString(", ")
	if v := _m.DraftCoverAssetID; v != nil {
		builder.WriteString("draft_cover_asset_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PublishedCoverAssetID; v != nil {
		builder.WriteString("published_cover_asset_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.HomePosition; v != nil {
		builder.WriteString("home_position=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedBy))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedBy))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ImageCreationTemplates is a parsable slice of ImageCreationTemplate.
type ImageCreationTemplates []*ImageCreationTemplate
