// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/paymentplan"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PaymentOrderUpdate is the builder for updating PaymentOrder entities.
type PaymentOrderUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdate) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *PaymentOrderUpdate) SetOrderNo(v string) *PaymentOrderUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableOrderNo(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentOrderUpdate) SetUserID(v int64) *PaymentOrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableUserID(v *int64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *PaymentOrderUpdate) SetType(v string) *PaymentOrderUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableType(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *PaymentOrderUpdate) SetPlanID(v int64) *PaymentOrderUpdate {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillablePlanID(v *int64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// ClearPlanID clears the value of the "plan_id" field.
func (_u *PaymentOrderUpdate) ClearPlanID() *PaymentOrderUpdate {
	_u.mutation.ClearPlanID()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentOrderUpdate) SetAmount(v float64) *PaymentOrderUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableAmount(v *float64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentOrderUpdate) AddAmount(v float64) *PaymentOrderUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCreditAmount sets the "credit_amount" field.
func (_u *PaymentOrderUpdate) SetCreditAmount(v float64) *PaymentOrderUpdate {
	_u.mutation.ResetCreditAmount()
	_u.mutation.SetCreditAmount(v)
	return _u
}

// SetNillableCreditAmount sets the "credit_amount" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableCreditAmount(v *float64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetCreditAmount(*v)
	}
	return _u
}

// AddCreditAmount adds value to the "credit_amount" field.
func (_u *PaymentOrderUpdate) AddCreditAmount(v float64) *PaymentOrderUpdate {
	_u.mutation.AddCreditAmount(v)
	return _u
}

// ClearCreditAmount clears the value of the "credit_amount" field.
func (_u *PaymentOrderUpdate) ClearCreditAmount() *PaymentOrderUpdate {
	_u.mutation.ClearCreditAmount()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentOrderUpdate) SetCurrency(v string) *PaymentOrderUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableCurrency(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdate) SetStatus(v string) *PaymentOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableStatus(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *PaymentOrderUpdate) SetProvider(v string) *PaymentOrderUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableProvider(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// ClearProvider clears the value of the "provider" field.
func (_u *PaymentOrderUpdate) ClearProvider() *PaymentOrderUpdate {
	_u.mutation.ClearProvider()
	return _u
}

// SetProviderOrderNo sets the "provider_order_no" field.
func (_u *PaymentOrderUpdate) SetProviderOrderNo(v string) *PaymentOrderUpdate {
	_u.mutation.SetProviderOrderNo(v)
	return _u
}

// SetNillableProviderOrderNo sets the "provider_order_no" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableProviderOrderNo(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetProviderOrderNo(*v)
	}
	return _u
}

// ClearProviderOrderNo clears the value of the "provider_order_no" field.
func (_u *PaymentOrderUpdate) ClearProviderOrderNo() *PaymentOrderUpdate {
	_u.mutation.ClearProviderOrderNo()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentOrderUpdate) SetPaidAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillablePaidAt(v *time.Time) *PaymentOrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentOrderUpdate) ClearPaidAt() *PaymentOrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *PaymentOrderUpdate) SetCompletedAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableCompletedAt(v *time.Time) *PaymentOrderUpdate {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *PaymentOrderUpdate) ClearCompletedAt() *PaymentOrderUpdate {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetRefundedAt sets the "refunded_at" field.
func (_u *PaymentOrderUpdate) SetRefundedAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetRefundedAt(v)
	return _u
}

// SetNillableRefundedAt sets the "refunded_at" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableRefundedAt(v *time.Time) *PaymentOrderUpdate {
	if v != nil {
		_u.SetRefundedAt(*v)
	}
	return _u
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (_u *PaymentOrderUpdate) ClearRefundedAt() *PaymentOrderUpdate {
	_u.mutation.ClearRefundedAt()
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *PaymentOrderUpdate) SetExpiredAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableExpiredAt(v *time.Time) *PaymentOrderUpdate {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// SetCallbackRaw sets the "callback_raw" field.
func (_u *PaymentOrderUpdate) SetCallbackRaw(v string) *PaymentOrderUpdate {
	_u.mutation.SetCallbackRaw(v)
	return _u
}

// SetNillableCallbackRaw sets the "callback_raw" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableCallbackRaw(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetCallbackRaw(*v)
	}
	return _u
}

// ClearCallbackRaw clears the value of the "callback_raw" field.
func (_u *PaymentOrderUpdate) ClearCallbackRaw() *PaymentOrderUpdate {
	_u.mutation.ClearCallbackRaw()
	return _u
}

// SetAdminNote sets the "admin_note" field.
func (_u *PaymentOrderUpdate) SetAdminNote(v string) *PaymentOrderUpdate {
	_u.mutation.SetAdminNote(v)
	return _u
}

// SetNillableAdminNote sets the "admin_note" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableAdminNote(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetAdminNote(*v)
	}
	return _u
}

// ClearAdminNote clears the value of the "admin_note" field.
func (_u *PaymentOrderUpdate) ClearAdminNote() *PaymentOrderUpdate {
	_u.mutation.ClearAdminNote()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentOrderUpdate) SetUpdatedAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentOrderUpdate) SetUser(v *User) *PaymentOrderUpdate {
	return _u.SetUserID(v.ID)
}

// SetPlan sets the "plan" edge to the PaymentPlan entity.
func (_u *PaymentOrderUpdate) SetPlan(v *PaymentPlan) *PaymentOrderUpdate {
	return _u.SetPlanID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdate) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentOrderUpdate) ClearUser() *PaymentOrderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearPlan clears the "plan" edge to the PaymentPlan entity.
func (_u *PaymentOrderUpdate) ClearPlan() *PaymentOrderUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentOrderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentOrderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentOrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := paymentorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := paymentorder.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := paymentorder.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := paymentorder.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderOrderNo(); ok {
		if err := paymentorder.ProviderOrderNoValidator(v); err != nil {
			return &ValidationError{Name: "provider_order_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider_order_no": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentOrder.user"`)
	}
	return nil
}

func (_u *PaymentOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(paymentorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(paymentorder.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(paymentorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(paymentorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreditAmount(); ok {
		_spec.SetField(paymentorder.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditAmount(); ok {
		_spec.AddField(paymentorder.FieldCreditAmount, field.TypeFloat64, value)
	}
	if _u.mutation.CreditAmountCleared() {
		_spec.ClearField(paymentorder.FieldCreditAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(paymentorder.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(paymentorder.FieldProvider, field.TypeString, value)
	}
	if _u.mutation.ProviderCleared() {
		_spec.ClearField(paymentorder.FieldProvider, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderOrderNo(); ok {
		_spec.SetField(paymentorder.FieldProviderOrderNo, field.TypeString, value)
	}
	if _u.mutation.ProviderOrderNoCleared() {
		_spec.ClearField(paymentorder.FieldProviderOrderNo, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paymentorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(paymentorder.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(paymentorder.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RefundedAt(); ok {
		_spec.SetField(paymentorder.FieldRefundedAt, field.TypeTime, value)
	}
	if _u.mutation.RefundedAtCleared() {
		_spec.ClearField(paymentorder.FieldRefundedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(paymentorder.FieldExpiredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CallbackRaw(); ok {
		_spec.SetField(paymentorder.FieldCallbackRaw, field.TypeString, value)
	}
	if _u.mutation.CallbackRawCleared() {
		_spec.ClearField(paymentorder.FieldCallbackRaw, field.TypeString)
	}
	if value, ok := _u.mutation.AdminNote(); ok {
		_spec.SetField(paymentorder.FieldAdminNote, field.TypeString, value)
	}
	if _u.mutation.AdminNoteCleared() {
		_spec.ClearField(paymentorder.FieldAdminNote, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.PlanTable,
			Columns: []string{paymentorder.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.PlanTable,
			Columns: []string{paymentorder.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentOrderUpdateOne is the builder for updating a single PaymentOrder entity.
type PaymentOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// SetOrderNo sets the "order_no" field.
func (_u *PaymentOrderUpdateOne) SetOrderNo(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableOrderNo(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentOrderUpdateOne) SetUserID(v int64) *PaymentOrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableUserID(v *int64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *PaymentOrderUpdateOne) SetType(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableType(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *PaymentOrderUpdateOne) SetPlanID(v int64) *PaymentOrderUpdateOne {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillablePlanID(v *int64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// ClearPlanID clears the value of the "plan_id" field.
func (_u *PaymentOrderUpdateOne) ClearPlanID() *PaymentOrderUpdateOne {
	_u.mutation.ClearPlanID()
	return _u
}

// SetAmount sets the "amount" field.
func (_u *PaymentOrderUpdateOne) SetAmount(v float64) *PaymentOrderUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableAmount(v *float64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *PaymentOrderUpdateOne) AddAmount(v float64) *PaymentOrderUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCreditAmount sets the "credit_amount" field.
func (_u *PaymentOrderUpdateOne) SetCreditAmount(v float64) *PaymentOrderUpdateOne {
	_u.mutation.ResetCreditAmount()
	_u.mutation.SetCreditAmount(v)
	return _u
}

// SetNillableCreditAmount sets the "credit_amount" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableCreditAmount(v *float64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetCreditAmount(*v)
	}
	return _u
}

// AddCreditAmount adds value to the "credit_amount" field.
func (_u *PaymentOrderUpdateOne) AddCreditAmount(v float64) *PaymentOrderUpdateOne {
	_u.mutation.AddCreditAmount(v)
	return _u
}

// ClearCreditAmount clears the value of the "credit_amount" field.
func (_u *PaymentOrderUpdateOne) ClearCreditAmount() *PaymentOrderUpdateOne {
	_u.mutation.ClearCreditAmount()
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *PaymentOrderUpdateOne) SetCurrency(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableCurrency(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdateOne) SetStatus(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableStatus(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *PaymentOrderUpdateOne) SetProvider(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableProvider(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// ClearProvider clears the value of the "provider" field.
func (_u *PaymentOrderUpdateOne) ClearProvider() *PaymentOrderUpdateOne {
	_u.mutation.ClearProvider()
	return _u
}

// SetProviderOrderNo sets the "provider_order_no" field.
func (_u *PaymentOrderUpdateOne) SetProviderOrderNo(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetProviderOrderNo(v)
	return _u
}

// SetNillableProviderOrderNo sets the "provider_order_no" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableProviderOrderNo(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetProviderOrderNo(*v)
	}
	return _u
}

// ClearProviderOrderNo clears the value of the "provider_order_no" field.
func (_u *PaymentOrderUpdateOne) ClearProviderOrderNo() *PaymentOrderUpdateOne {
	_u.mutation.ClearProviderOrderNo()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentOrderUpdateOne) SetPaidAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillablePaidAt(v *time.Time) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentOrderUpdateOne) ClearPaidAt() *PaymentOrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetCompletedAt sets the "completed_at" field.
func (_u *PaymentOrderUpdateOne) SetCompletedAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetCompletedAt(v)
	return _u
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableCompletedAt(v *time.Time) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetCompletedAt(*v)
	}
	return _u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (_u *PaymentOrderUpdateOne) ClearCompletedAt() *PaymentOrderUpdateOne {
	_u.mutation.ClearCompletedAt()
	return _u
}

// SetRefundedAt sets the "refunded_at" field.
func (_u *PaymentOrderUpdateOne) SetRefundedAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetRefundedAt(v)
	return _u
}

// SetNillableRefundedAt sets the "refunded_at" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableRefundedAt(v *time.Time) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetRefundedAt(*v)
	}
	return _u
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (_u *PaymentOrderUpdateOne) ClearRefundedAt() *PaymentOrderUpdateOne {
	_u.mutation.ClearRefundedAt()
	return _u
}

// SetExpiredAt sets the "expired_at" field.
func (_u *PaymentOrderUpdateOne) SetExpiredAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetExpiredAt(v)
	return _u
}

// SetNillableExpiredAt sets the "expired_at" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableExpiredAt(v *time.Time) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetExpiredAt(*v)
	}
	return _u
}

// SetCallbackRaw sets the "callback_raw" field.
func (_u *PaymentOrderUpdateOne) SetCallbackRaw(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetCallbackRaw(v)
	return _u
}

// SetNillableCallbackRaw sets the "callback_raw" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableCallbackRaw(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetCallbackRaw(*v)
	}
	return _u
}

// ClearCallbackRaw clears the value of the "callback_raw" field.
func (_u *PaymentOrderUpdateOne) ClearCallbackRaw() *PaymentOrderUpdateOne {
	_u.mutation.ClearCallbackRaw()
	return _u
}

// SetAdminNote sets the "admin_note" field.
func (_u *PaymentOrderUpdateOne) SetAdminNote(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetAdminNote(v)
	return _u
}

// SetNillableAdminNote sets the "admin_note" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableAdminNote(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetAdminNote(*v)
	}
	return _u
}

// ClearAdminNote clears the value of the "admin_note" field.
func (_u *PaymentOrderUpdateOne) ClearAdminNote() *PaymentOrderUpdateOne {
	_u.mutation.ClearAdminNote()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentOrderUpdateOne) SetUpdatedAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentOrderUpdateOne) SetUser(v *User) *PaymentOrderUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetPlan sets the "plan" edge to the PaymentPlan entity.
func (_u *PaymentOrderUpdateOne) SetPlan(v *PaymentPlan) *PaymentOrderUpdateOne {
	return _u.SetPlanID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdateOne) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentOrderUpdateOne) ClearUser() *PaymentOrderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearPlan clears the "plan" edge to the PaymentPlan entity.
func (_u *PaymentOrderUpdateOne) ClearPlan() *PaymentOrderUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdateOne) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentOrderUpdateOne) Select(field string, fields ...string) *PaymentOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentOrder entity.
func (_u *PaymentOrderUpdateOne) Save(ctx context.Context) (*PaymentOrder, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) SaveX(ctx context.Context) *PaymentOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentOrderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := paymentorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentOrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := paymentorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := paymentorder.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := paymentorder.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Provider(); ok {
		if err := paymentorder.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderOrderNo(); ok {
		if err := paymentorder.ProviderOrderNoValidator(v); err != nil {
			return &ValidationError{Name: "provider_order_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider_order_no": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentOrder.user"`)
	}
	return nil
}

func (_u *PaymentOrderUpdateOne) sqlSave(ctx context.Context) (_node *PaymentOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentorder.FieldID)
		for _, f := range fields {
			if !paymentorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(paymentorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(paymentorder.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(paymentorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(paymentorder.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreditAmount(); ok {
		_spec.SetField(paymentorder.FieldCreditAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreditAmount(); ok {
		_spec.AddField(paymentorder.FieldCreditAmount, field.TypeFloat64, value)
	}
	if _u.mutation.CreditAmountCleared() {
		_spec.ClearField(paymentorder.FieldCreditAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(paymentorder.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(paymentorder.FieldProvider, field.TypeString, value)
	}
	if _u.mutation.ProviderCleared() {
		_spec.ClearField(paymentorder.FieldProvider, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderOrderNo(); ok {
		_spec.SetField(paymentorder.FieldProviderOrderNo, field.TypeString, value)
	}
	if _u.mutation.ProviderOrderNoCleared() {
		_spec.ClearField(paymentorder.FieldProviderOrderNo, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paymentorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CompletedAt(); ok {
		_spec.SetField(paymentorder.FieldCompletedAt, field.TypeTime, value)
	}
	if _u.mutation.CompletedAtCleared() {
		_spec.ClearField(paymentorder.FieldCompletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RefundedAt(); ok {
		_spec.SetField(paymentorder.FieldRefundedAt, field.TypeTime, value)
	}
	if _u.mutation.RefundedAtCleared() {
		_spec.ClearField(paymentorder.FieldRefundedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ExpiredAt(); ok {
		_spec.SetField(paymentorder.FieldExpiredAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CallbackRaw(); ok {
		_spec.SetField(paymentorder.FieldCallbackRaw, field.TypeString, value)
	}
	if _u.mutation.CallbackRawCleared() {
		_spec.ClearField(paymentorder.FieldCallbackRaw, field.TypeString)
	}
	if value, ok := _u.mutation.AdminNote(); ok {
		_spec.SetField(paymentorder.FieldAdminNote, field.TypeString, value)
	}
	if _u.mutation.AdminNoteCleared() {
		_spec.ClearField(paymentorder.FieldAdminNote, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.PlanTable,
			Columns: []string{paymentorder.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.PlanTable,
			Columns: []string{paymentorder.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
