// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/paymentplan"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PaymentPlanUpdate is the builder for updating PaymentPlan entities.
type PaymentPlanUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentPlanMutation
}

// Where appends a list predicates to the PaymentPlanUpdate builder.
func (_u *PaymentPlanUpdate) Where(ps ...predicate.PaymentPlan) *PaymentPlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentPlanUpdate) SetUpdatedAt(v time.Time) *PaymentPlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PaymentPlanUpdate) SetDeletedAt(v time.Time) *PaymentPlanUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PaymentPlanUpdate) SetNillableDeletedAt(v *time.Time) *PaymentPlanUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PaymentPlanUpdate) ClearDeletedAt() *PaymentPlanUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *PaymentPlanUpdate) SetName(v string) *PaymentPlanUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PaymentPlanUpdate) SetNillableName(v *string) *PaymentPlanUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PaymentPlanUpdate) SetDescription(v string) *PaymentPlanUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PaymentPlanUpdate) SetNillableDescription(v *string) *PaymentPlanUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetBadge sets the "badge" field.
func (_u *PaymentPlanUpdate) SetBadge(v string) *PaymentPlanUpdate {
	_u.mutation.SetBadge(v)
	return _u
}

// SetNillableBadge sets the "badge" field if the given value is not nil.
func (_u *PaymentPlanUpdate) SetNillableBadge(v *string) *PaymentPlanUpdate {
	if v != nil {
		_u.SetBadge(*v)
	}
	return _u
}

// ClearBadge clears the value of the "badge" field.
func (_u *PaymentPlanUpdate) ClearBadge() *PaymentPlanUpdate {
	_u.mutation.ClearBadge()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *PaymentPlanUpdate) SetGroupID(v int64) *PaymentPlanUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *PaymentPlanUpdate) SetNillableGroupID(v *int64) *PaymentPlanUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetDurationDays sets the "duration_days" field.
func (_u *PaymentPlanUpdate) SetDurationDays(v int) *PaymentPlanUpdate {
	_u.mutation.ResetDurationDays()
	_u.mutation.SetDurationDays(v)
	return _u
}

// SetNillableDurationDays sets the "duration_days" field if the given value is not nil.
func (_u *PaymentPlanUpdate) SetNillableDurationDays(v *int) *PaymentPlanUpdate {
	if v != nil {
		_u.SetDurationDays(*v)
	}
	return _u
}

// AddDurationDays adds value to the "duration_days" field.
func (_u *PaymentPlanUpdate) AddDurationDays(v int) *PaymentPlanUpdate {
	_u.mutation.AddDurationDays(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *PaymentPlanUpdate) SetPrice(v float64) *PaymentPlanUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *PaymentPlanUpdate) SetNillablePrice(v *float64) *PaymentPlanUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *PaymentPlanUpdate) AddPrice(v float64) *PaymentPlanUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetOriginalPrice sets the "original_price" field.
func (_u *PaymentPlanUpdate) SetOriginalPrice(v float64) *PaymentPlanUpdate {
	_u.mutation.ResetOriginalPrice()
	_u.mutation.SetOriginalPrice(v)
	return _u
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_u *PaymentPlanUpdate) SetNillableOriginalPrice(v *float64) *PaymentPlanUpdate {
	if v != nil {
		_u.SetOriginalPrice(*v)
	}
	return _u
}

// AddOriginalPrice adds value to the "original_price" field.
func (_u *PaymentPlanUpdate) AddOriginalPrice(v float64) *PaymentPlanUpdate {
	_u.mutation.AddOriginalPrice(v)
	return _u
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (_u *PaymentPlanUpdate) ClearOriginalPrice() *PaymentPlanUpdate {
	_u.mutation.ClearOriginalPrice()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *PaymentPlanUpdate) SetSortOrder(v int) *PaymentPlanUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *PaymentPlanUpdate) SetNillableSortOrder(v *int) *PaymentPlanUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *PaymentPlanUpdate) AddSortOrder(v int) *PaymentPlanUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *PaymentPlanUpdate) SetIsActive(v bool) *PaymentPlanUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *PaymentPlanUpdate) SetNillableIsActive(v *bool) *PaymentPlanUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *PaymentPlanUpdate) SetGroup(v *Group) *PaymentPlanUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the PaymentPlanMutation object of the builder.
func (_u *PaymentPlanUpdate) Mutation() *PaymentPlanMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *PaymentPlanUpdate) ClearGroup() *PaymentPlanUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentPlanUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentPlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentPlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentPlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentPlanUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if paymentplan.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized paymentplan.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := paymentplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentPlanUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := paymentplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PaymentPlan.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Badge(); ok {
		if err := paymentplan.BadgeValidator(v); err != nil {
			return &ValidationError{Name: "badge", err: fmt.Errorf(`ent: validator failed for field "PaymentPlan.badge": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationDays(); ok {
		if err := paymentplan.DurationDaysValidator(v); err != nil {
			return &ValidationError{Name: "duration_days", err: fmt.Errorf(`ent: validator failed for field "PaymentPlan.duration_days": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SortOrder(); ok {
		if err := paymentplan.SortOrderValidator(v); err != nil {
			return &ValidationError{Name: "sort_order", err: fmt.Errorf(`ent: validator failed for field "PaymentPlan.sort_order": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentPlan.group"`)
	}
	return nil
}

func (_u *PaymentPlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentplan.Table, paymentplan.Columns, sqlgraph.NewFieldSpec(paymentplan.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(paymentplan.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(paymentplan.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(paymentplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(paymentplan.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Badge(); ok {
		_spec.SetField(paymentplan.FieldBadge, field.TypeString, value)
	}
	if _u.mutation.BadgeCleared() {
		_spec.ClearField(paymentplan.FieldBadge, field.TypeString)
	}
	if value, ok := _u.mutation.DurationDays(); ok {
		_spec.SetField(paymentplan.FieldDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationDays(); ok {
		_spec.AddField(paymentplan.FieldDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(paymentplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(paymentplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OriginalPrice(); ok {
		_spec.SetField(paymentplan.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginalPrice(); ok {
		_spec.AddField(paymentplan.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OriginalPriceCleared() {
		_spec.ClearField(paymentplan.FieldOriginalPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(paymentplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(paymentplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(paymentplan.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentplan.GroupTable,
			Columns: []string{paymentplan.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentplan.GroupTable,
			Columns: []string{paymentplan.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentPlanUpdateOne is the builder for updating a single PaymentPlan entity.
type PaymentPlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentPlanMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentPlanUpdateOne) SetUpdatedAt(v time.Time) *PaymentPlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PaymentPlanUpdateOne) SetDeletedAt(v time.Time) *PaymentPlanUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PaymentPlanUpdateOne) SetNillableDeletedAt(v *time.Time) *PaymentPlanUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PaymentPlanUpdateOne) ClearDeletedAt() *PaymentPlanUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *PaymentPlanUpdateOne) SetName(v string) *PaymentPlanUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PaymentPlanUpdateOne) SetNillableName(v *string) *PaymentPlanUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PaymentPlanUpdateOne) SetDescription(v string) *PaymentPlanUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PaymentPlanUpdateOne) SetNillableDescription(v *string) *PaymentPlanUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetBadge sets the "badge" field.
func (_u *PaymentPlanUpdateOne) SetBadge(v string) *PaymentPlanUpdateOne {
	_u.mutation.SetBadge(v)
	return _u
}

// SetNillableBadge sets the "badge" field if the given value is not nil.
func (_u *PaymentPlanUpdateOne) SetNillableBadge(v *string) *PaymentPlanUpdateOne {
	if v != nil {
		_u.SetBadge(*v)
	}
	return _u
}

// ClearBadge clears the value of the "badge" field.
func (_u *PaymentPlanUpdateOne) ClearBadge() *PaymentPlanUpdateOne {
	_u.mutation.ClearBadge()
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *PaymentPlanUpdateOne) SetGroupID(v int64) *PaymentPlanUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *PaymentPlanUpdateOne) SetNillableGroupID(v *int64) *PaymentPlanUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetDurationDays sets the "duration_days" field.
func (_u *PaymentPlanUpdateOne) SetDurationDays(v int) *PaymentPlanUpdateOne {
	_u.mutation.ResetDurationDays()
	_u.mutation.SetDurationDays(v)
	return _u
}

// SetNillableDurationDays sets the "duration_days" field if the given value is not nil.
func (_u *PaymentPlanUpdateOne) SetNillableDurationDays(v *int) *PaymentPlanUpdateOne {
	if v != nil {
		_u.SetDurationDays(*v)
	}
	return _u
}

// AddDurationDays adds value to the "duration_days" field.
func (_u *PaymentPlanUpdateOne) AddDurationDays(v int) *PaymentPlanUpdateOne {
	_u.mutation.AddDurationDays(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *PaymentPlanUpdateOne) SetPrice(v float64) *PaymentPlanUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *PaymentPlanUpdateOne) SetNillablePrice(v *float64) *PaymentPlanUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *PaymentPlanUpdateOne) AddPrice(v float64) *PaymentPlanUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetOriginalPrice sets the "original_price" field.
func (_u *PaymentPlanUpdateOne) SetOriginalPrice(v float64) *PaymentPlanUpdateOne {
	_u.mutation.ResetOriginalPrice()
	_u.mutation.SetOriginalPrice(v)
	return _u
}

// SetNillableOriginalPrice sets the "original_price" field if the given value is not nil.
func (_u *PaymentPlanUpdateOne) SetNillableOriginalPrice(v *float64) *PaymentPlanUpdateOne {
	if v != nil {
		_u.SetOriginalPrice(*v)
	}
	return _u
}

// AddOriginalPrice adds value to the "original_price" field.
func (_u *PaymentPlanUpdateOne) AddOriginalPrice(v float64) *PaymentPlanUpdateOne {
	_u.mutation.AddOriginalPrice(v)
	return _u
}

// ClearOriginalPrice clears the value of the "original_price" field.
func (_u *PaymentPlanUpdateOne) ClearOriginalPrice() *PaymentPlanUpdateOne {
	_u.mutation.ClearOriginalPrice()
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *PaymentPlanUpdateOne) SetSortOrder(v int) *PaymentPlanUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *PaymentPlanUpdateOne) SetNillableSortOrder(v *int) *PaymentPlanUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *PaymentPlanUpdateOne) AddSortOrder(v int) *PaymentPlanUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *PaymentPlanUpdateOne) SetIsActive(v bool) *PaymentPlanUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *PaymentPlanUpdateOne) SetNillableIsActive(v *bool) *PaymentPlanUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *PaymentPlanUpdateOne) SetGroup(v *Group) *PaymentPlanUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the PaymentPlanMutation object of the builder.
func (_u *PaymentPlanUpdateOne) Mutation() *PaymentPlanMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *PaymentPlanUpdateOne) ClearGroup() *PaymentPlanUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the PaymentPlanUpdate builder.
func (_u *PaymentPlanUpdateOne) Where(ps ...predicate.PaymentPlan) *PaymentPlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentPlanUpdateOne) Select(field string, fields ...string) *PaymentPlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentPlan entity.
func (_u *PaymentPlanUpdateOne) Save(ctx context.Context) (*PaymentPlan, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentPlanUpdateOne) SaveX(ctx context.Context) *PaymentPlan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentPlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentPlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentPlanUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if paymentplan.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized paymentplan.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := paymentplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentPlanUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := paymentplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PaymentPlan.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Badge(); ok {
		if err := paymentplan.BadgeValidator(v); err != nil {
			return &ValidationError{Name: "badge", err: fmt.Errorf(`ent: validator failed for field "PaymentPlan.badge": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DurationDays(); ok {
		if err := paymentplan.DurationDaysValidator(v); err != nil {
			return &ValidationError{Name: "duration_days", err: fmt.Errorf(`ent: validator failed for field "PaymentPlan.duration_days": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SortOrder(); ok {
		if err := paymentplan.SortOrderValidator(v); err != nil {
			return &ValidationError{Name: "sort_order", err: fmt.Errorf(`ent: validator failed for field "PaymentPlan.sort_order": %w`, err)}
		}
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentPlan.group"`)
	}
	return nil
}

func (_u *PaymentPlanUpdateOne) sqlSave(ctx context.Context) (_node *PaymentPlan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentplan.Table, paymentplan.Columns, sqlgraph.NewFieldSpec(paymentplan.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentPlan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentplan.FieldID)
		for _, f := range fields {
			if !paymentplan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(paymentplan.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(paymentplan.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(paymentplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(paymentplan.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Badge(); ok {
		_spec.SetField(paymentplan.FieldBadge, field.TypeString, value)
	}
	if _u.mutation.BadgeCleared() {
		_spec.ClearField(paymentplan.FieldBadge, field.TypeString)
	}
	if value, ok := _u.mutation.DurationDays(); ok {
		_spec.SetField(paymentplan.FieldDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationDays(); ok {
		_spec.AddField(paymentplan.FieldDurationDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(paymentplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(paymentplan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OriginalPrice(); ok {
		_spec.SetField(paymentplan.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOriginalPrice(); ok {
		_spec.AddField(paymentplan.FieldOriginalPrice, field.TypeFloat64, value)
	}
	if _u.mutation.OriginalPriceCleared() {
		_spec.ClearField(paymentplan.FieldOriginalPrice, field.TypeFloat64)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(paymentplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(paymentplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(paymentplan.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentplan.GroupTable,
			Columns: []string{paymentplan.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentplan.GroupTable,
			Columns: []string{paymentplan.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentPlan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
