// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/paymentplan"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PaymentOrderCreate is the builder for creating a PaymentOrder entity.
type PaymentOrderCreate struct {
	config
	mutation *PaymentOrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOrderNo sets the "order_no" field.
func (_c *PaymentOrderCreate) SetOrderNo(v string) *PaymentOrderCreate {
	_c.mutation.SetOrderNo(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *PaymentOrderCreate) SetUserID(v int64) *PaymentOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *PaymentOrderCreate) SetType(v string) *PaymentOrderCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *PaymentOrderCreate) SetPlanID(v int64) *PaymentOrderCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillablePlanID(v *int64) *PaymentOrderCreate {
	if v != nil {
		_c.SetPlanID(*v)
	}
	return _c
}

// SetAmount sets the "amount" field.
func (_c *PaymentOrderCreate) SetAmount(v float64) *PaymentOrderCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableAmount(v *float64) *PaymentOrderCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetCreditAmount sets the "credit_amount" field.
func (_c *PaymentOrderCreate) SetCreditAmount(v float64) *PaymentOrderCreate {
	_c.mutation.SetCreditAmount(v)
	return _c
}

// SetNillableCreditAmount sets the "credit_amount" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableCreditAmount(v *float64) *PaymentOrderCreate {
	if v != nil {
		_c.SetCreditAmount(*v)
	}
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *PaymentOrderCreate) SetCurrency(v string) *PaymentOrderCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableCurrency(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetCurrency(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentOrderCreate) SetStatus(v string) *PaymentOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableStatus(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetProvider sets the "provider" field.
func (_c *PaymentOrderCreate) SetProvider(v string) *PaymentOrderCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableProvider(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetProviderOrderNo sets the "provider_order_no" field.
func (_c *PaymentOrderCreate) SetProviderOrderNo(v string) *PaymentOrderCreate {
	_c.mutation.SetProviderOrderNo(v)
	return _c
}

// SetNillableProviderOrderNo sets the "provider_order_no" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableProviderOrderNo(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetProviderOrderNo(*v)
	}
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *PaymentOrderCreate) SetPaidAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillablePaidAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *PaymentOrderCreate) SetCompletedAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableCompletedAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetRefundedAt sets the "refunded_at" field.
func (_c *PaymentOrderCreate) SetRefundedAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetRefundedAt(v)
	return _c
}

// SetNillableRefundedAt sets the "refunded_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableRefundedAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetRefundedAt(*v)
	}
	return _c
}

// SetExpiredAt sets the "expired_at" field.
func (_c *PaymentOrderCreate) SetExpiredAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetExpiredAt(v)
	return _c
}

// SetCallbackRaw sets the "callback_raw" field.
func (_c *PaymentOrderCreate) SetCallbackRaw(v string) *PaymentOrderCreate {
	_c.mutation.SetCallbackRaw(v)
	return _c
}

// SetNillableCallbackRaw sets the "callback_raw" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableCallbackRaw(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetCallbackRaw(*v)
	}
	return _c
}

// SetAdminNote sets the "admin_note" field.
func (_c *PaymentOrderCreate) SetAdminNote(v string) *PaymentOrderCreate {
	_c.mutation.SetAdminNote(v)
	return _c
}

// SetNillableAdminNote sets the "admin_note" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableAdminNote(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetAdminNote(*v)
	}
	return _c
}

// SetRefundNo sets the "refund_no" field.
func (_c *PaymentOrderCreate) SetRefundNo(v string) *PaymentOrderCreate {
	_c.mutation.SetRefundNo(v)
	return _c
}

// SetNillableRefundNo sets the "refund_no" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableRefundNo(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetRefundNo(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentOrderCreate) SetCreatedAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableCreatedAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PaymentOrderCreate) SetUpdatedAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableUpdatedAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PaymentOrderCreate) SetUser(v *User) *PaymentOrderCreate {
	return _c.SetUserID(v.ID)
}

// SetPlan sets the "plan" edge to the PaymentPlan entity.
func (_c *PaymentOrderCreate) SetPlan(v *PaymentPlan) *PaymentOrderCreate {
	return _c.SetPlanID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_c *PaymentOrderCreate) Mutation() *PaymentOrderMutation {
	return _c.mutation
}

// Save creates the PaymentOrder in the database.
func (_c *PaymentOrderCreate) Save(ctx context.Context) (*PaymentOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentOrderCreate) SaveX(ctx context.Context) *PaymentOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentOrderCreate) defaults() {
	if _, ok := _c.mutation.Amount(); !ok {
		v := paymentorder.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.Currency(); !ok {
		v := paymentorder.DefaultCurrency
		_c.mutation.SetCurrency(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := paymentorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paymentorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := paymentorder.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentOrderCreate) check() error {
	if _, ok := _c.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "PaymentOrder.order_no"`)}
	}
	if v, ok := _c.mutation.OrderNo(); ok {
		if err := paymentorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PaymentOrder.user_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "PaymentOrder.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := paymentorder.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "PaymentOrder.amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`ent: missing required field "PaymentOrder.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := paymentorder.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := paymentorder.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ProviderOrderNo(); ok {
		if err := paymentorder.ProviderOrderNoValidator(v); err != nil {
			return &ValidationError{Name: "provider_order_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.provider_order_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiredAt(); !ok {
		return &ValidationError{Name: "expired_at", err: errors.New(`ent: missing required field "PaymentOrder.expired_at"`)}
	}
	if v, ok := _c.mutation.RefundNo(); ok {
		if err := paymentorder.RefundNoValidator(v); err != nil {
			return &ValidationError{Name: "refund_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.refund_no": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentOrder.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PaymentOrder.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "PaymentOrder.user"`)}
	}
	return nil
}

func (_c *PaymentOrderCreate) sqlSave(ctx context.Context) (*PaymentOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentOrderCreate) createSpec() (*PaymentOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentorder.Table, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.OrderNo(); ok {
		_spec.SetField(paymentorder.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(paymentorder.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(paymentorder.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.CreditAmount(); ok {
		_spec.SetField(paymentorder.FieldCreditAmount, field.TypeFloat64, value)
		_node.CreditAmount = &value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(paymentorder.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(paymentorder.FieldProvider, field.TypeString, value)
		_node.Provider = &value
	}
	if value, ok := _c.mutation.ProviderOrderNo(); ok {
		_spec.SetField(paymentorder.FieldProviderOrderNo, field.TypeString, value)
		_node.ProviderOrderNo = &value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(paymentorder.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.RefundedAt(); ok {
		_spec.SetField(paymentorder.FieldRefundedAt, field.TypeTime, value)
		_node.RefundedAt = &value
	}
	if value, ok := _c.mutation.ExpiredAt(); ok {
		_spec.SetField(paymentorder.FieldExpiredAt, field.TypeTime, value)
		_node.ExpiredAt = value
	}
	if value, ok := _c.mutation.CallbackRaw(); ok {
		_spec.SetField(paymentorder.FieldCallbackRaw, field.TypeString, value)
		_node.CallbackRaw = &value
	}
	if value, ok := _c.mutation.AdminNote(); ok {
		_spec.SetField(paymentorder.FieldAdminNote, field.TypeString, value)
		_node.AdminNote = &value
	}
	if value, ok := _c.mutation.RefundNo(); ok {
		_spec.SetField(paymentorder.FieldRefundNo, field.TypeString, value)
		_node.RefundNo = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymentorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.PlanTable,
			Columns: []string{paymentorder.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlanID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentOrder.Create().
//		SetOrderNo(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentOrderUpsert) {
//			SetOrderNo(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentOrderCreate) OnConflict(opts ...sql.ConflictOption) *PaymentOrderUpsertOne {
	_c.conflict = opts
	return &PaymentOrderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentOrderCreate) OnConflictColumns(columns ...string) *PaymentOrderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentOrderUpsertOne{
		create: _c,
	}
}

type (
	// PaymentOrderUpsertOne is the builder for "upsert"-ing
	//  one PaymentOrder node.
	PaymentOrderUpsertOne struct {
		create *PaymentOrderCreate
	}

	// PaymentOrderUpsert is the "OnConflict" setter.
	PaymentOrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetOrderNo sets the "order_no" field.
func (u *PaymentOrderUpsert) SetOrderNo(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldOrderNo, v)
	return u
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateOrderNo() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldOrderNo)
	return u
}

// SetUserID sets the "user_id" field.
func (u *PaymentOrderUpsert) SetUserID(v int64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateUserID() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldUserID)
	return u
}

// SetType sets the "type" field.
func (u *PaymentOrderUpsert) SetType(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateType() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldType)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *PaymentOrderUpsert) SetPlanID(v int64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdatePlanID() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldPlanID)
	return u
}

// ClearPlanID clears the value of the "plan_id" field.
func (u *PaymentOrderUpsert) ClearPlanID() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldPlanID)
	return u
}

// SetAmount sets the "amount" field.
func (u *PaymentOrderUpsert) SetAmount(v float64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateAmount() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *PaymentOrderUpsert) AddAmount(v float64) *PaymentOrderUpsert {
	u.Add(paymentorder.FieldAmount, v)
	return u
}

// SetCreditAmount sets the "credit_amount" field.
func (u *PaymentOrderUpsert) SetCreditAmount(v float64) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldCreditAmount, v)
	return u
}

// UpdateCreditAmount sets the "credit_amount" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateCreditAmount() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldCreditAmount)
	return u
}

// AddCreditAmount adds v to the "credit_amount" field.
func (u *PaymentOrderUpsert) AddCreditAmount(v float64) *PaymentOrderUpsert {
	u.Add(paymentorder.FieldCreditAmount, v)
	return u
}

// ClearCreditAmount clears the value of the "credit_amount" field.
func (u *PaymentOrderUpsert) ClearCreditAmount() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldCreditAmount)
	return u
}

// SetCurrency sets the "currency" field.
func (u *PaymentOrderUpsert) SetCurrency(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateCurrency() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldCurrency)
	return u
}

// SetStatus sets the "status" field.
func (u *PaymentOrderUpsert) SetStatus(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateStatus() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldStatus)
	return u
}

// SetProvider sets the "provider" field.
func (u *PaymentOrderUpsert) SetProvider(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateProvider() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldProvider)
	return u
}

// ClearProvider clears the value of the "provider" field.
func (u *PaymentOrderUpsert) ClearProvider() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldProvider)
	return u
}

// SetProviderOrderNo sets the "provider_order_no" field.
func (u *PaymentOrderUpsert) SetProviderOrderNo(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldProviderOrderNo, v)
	return u
}

// UpdateProviderOrderNo sets the "provider_order_no" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateProviderOrderNo() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldProviderOrderNo)
	return u
}

// ClearProviderOrderNo clears the value of the "provider_order_no" field.
func (u *PaymentOrderUpsert) ClearProviderOrderNo() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldProviderOrderNo)
	return u
}

// SetPaidAt sets the "paid_at" field.
func (u *PaymentOrderUpsert) SetPaidAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldPaidAt, v)
	return u
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdatePaidAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldPaidAt)
	return u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaymentOrderUpsert) ClearPaidAt() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldPaidAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *PaymentOrderUpsert) SetCompletedAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateCompletedAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *PaymentOrderUpsert) ClearCompletedAt() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldCompletedAt)
	return u
}

// SetRefundedAt sets the "refunded_at" field.
func (u *PaymentOrderUpsert) SetRefundedAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldRefundedAt, v)
	return u
}

// UpdateRefundedAt sets the "refunded_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateRefundedAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldRefundedAt)
	return u
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (u *PaymentOrderUpsert) ClearRefundedAt() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldRefundedAt)
	return u
}

// SetExpiredAt sets the "expired_at" field.
func (u *PaymentOrderUpsert) SetExpiredAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldExpiredAt, v)
	return u
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateExpiredAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldExpiredAt)
	return u
}

// SetCallbackRaw sets the "callback_raw" field.
func (u *PaymentOrderUpsert) SetCallbackRaw(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldCallbackRaw, v)
	return u
}

// UpdateCallbackRaw sets the "callback_raw" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateCallbackRaw() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldCallbackRaw)
	return u
}

// ClearCallbackRaw clears the value of the "callback_raw" field.
func (u *PaymentOrderUpsert) ClearCallbackRaw() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldCallbackRaw)
	return u
}

// SetAdminNote sets the "admin_note" field.
func (u *PaymentOrderUpsert) SetAdminNote(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldAdminNote, v)
	return u
}

// UpdateAdminNote sets the "admin_note" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateAdminNote() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldAdminNote)
	return u
}

// ClearAdminNote clears the value of the "admin_note" field.
func (u *PaymentOrderUpsert) ClearAdminNote() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldAdminNote)
	return u
}

// SetRefundNo sets the "refund_no" field.
func (u *PaymentOrderUpsert) SetRefundNo(v string) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldRefundNo, v)
	return u
}

// UpdateRefundNo sets the "refund_no" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateRefundNo() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldRefundNo)
	return u
}

// ClearRefundNo clears the value of the "refund_no" field.
func (u *PaymentOrderUpsert) ClearRefundNo() *PaymentOrderUpsert {
	u.SetNull(paymentorder.FieldRefundNo)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentOrderUpsert) SetUpdatedAt(v time.Time) *PaymentOrderUpsert {
	u.Set(paymentorder.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentOrderUpsert) UpdateUpdatedAt() *PaymentOrderUpsert {
	u.SetExcluded(paymentorder.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentOrderUpsertOne) UpdateNewValues() *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(paymentorder.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PaymentOrderUpsertOne) Ignore() *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentOrderUpsertOne) DoNothing() *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentOrderCreate.OnConflict
// documentation for more info.
func (u *PaymentOrderUpsertOne) Update(set func(*PaymentOrderUpsert)) *PaymentOrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *PaymentOrderUpsertOne) SetOrderNo(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateOrderNo() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *PaymentOrderUpsertOne) SetUserID(v int64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateUserID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetType sets the "type" field.
func (u *PaymentOrderUpsertOne) SetType(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateType() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateType()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *PaymentOrderUpsertOne) SetPlanID(v int64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdatePlanID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePlanID()
	})
}

// ClearPlanID clears the value of the "plan_id" field.
func (u *PaymentOrderUpsertOne) ClearPlanID() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearPlanID()
	})
}

// SetAmount sets the "amount" field.
func (u *PaymentOrderUpsertOne) SetAmount(v float64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *PaymentOrderUpsertOne) AddAmount(v float64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateAmount() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetCreditAmount sets the "credit_amount" field.
func (u *PaymentOrderUpsertOne) SetCreditAmount(v float64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetCreditAmount(v)
	})
}

// AddCreditAmount adds v to the "credit_amount" field.
func (u *PaymentOrderUpsertOne) AddCreditAmount(v float64) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddCreditAmount(v)
	})
}

// UpdateCreditAmount sets the "credit_amount" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateCreditAmount() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateCreditAmount()
	})
}

// ClearCreditAmount clears the value of the "credit_amount" field.
func (u *PaymentOrderUpsertOne) ClearCreditAmount() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearCreditAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *PaymentOrderUpsertOne) SetCurrency(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateCurrency() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateCurrency()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentOrderUpsertOne) SetStatus(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateStatus() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetProvider sets the "provider" field.
func (u *PaymentOrderUpsertOne) SetProvider(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateProvider() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProvider()
	})
}

// ClearProvider clears the value of the "provider" field.
func (u *PaymentOrderUpsertOne) ClearProvider() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearProvider()
	})
}

// SetProviderOrderNo sets the "provider_order_no" field.
func (u *PaymentOrderUpsertOne) SetProviderOrderNo(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProviderOrderNo(v)
	})
}

// UpdateProviderOrderNo sets the "provider_order_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateProviderOrderNo() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProviderOrderNo()
	})
}

// ClearProviderOrderNo clears the value of the "provider_order_no" field.
func (u *PaymentOrderUpsertOne) ClearProviderOrderNo() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearProviderOrderNo()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *PaymentOrderUpsertOne) SetPaidAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdatePaidAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaymentOrderUpsertOne) ClearPaidAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *PaymentOrderUpsertOne) SetCompletedAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateCompletedAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *PaymentOrderUpsertOne) ClearCompletedAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearCompletedAt()
	})
}

// SetRefundedAt sets the "refunded_at" field.
func (u *PaymentOrderUpsertOne) SetRefundedAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetRefundedAt(v)
	})
}

// UpdateRefundedAt sets the "refunded_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateRefundedAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateRefundedAt()
	})
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (u *PaymentOrderUpsertOne) ClearRefundedAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearRefundedAt()
	})
}

// SetExpiredAt sets the "expired_at" field.
func (u *PaymentOrderUpsertOne) SetExpiredAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetExpiredAt(v)
	})
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateExpiredAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateExpiredAt()
	})
}

// SetCallbackRaw sets the "callback_raw" field.
func (u *PaymentOrderUpsertOne) SetCallbackRaw(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetCallbackRaw(v)
	})
}

// UpdateCallbackRaw sets the "callback_raw" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateCallbackRaw() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateCallbackRaw()
	})
}

// ClearCallbackRaw clears the value of the "callback_raw" field.
func (u *PaymentOrderUpsertOne) ClearCallbackRaw() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearCallbackRaw()
	})
}

// SetAdminNote sets the "admin_note" field.
func (u *PaymentOrderUpsertOne) SetAdminNote(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAdminNote(v)
	})
}

// UpdateAdminNote sets the "admin_note" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateAdminNote() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAdminNote()
	})
}

// ClearAdminNote clears the value of the "admin_note" field.
func (u *PaymentOrderUpsertOne) ClearAdminNote() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearAdminNote()
	})
}

// SetRefundNo sets the "refund_no" field.
func (u *PaymentOrderUpsertOne) SetRefundNo(v string) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetRefundNo(v)
	})
}

// UpdateRefundNo sets the "refund_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateRefundNo() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateRefundNo()
	})
}

// ClearRefundNo clears the value of the "refund_no" field.
func (u *PaymentOrderUpsertOne) ClearRefundNo() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearRefundNo()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentOrderUpsertOne) SetUpdatedAt(v time.Time) *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertOne) UpdateUpdatedAt() *PaymentOrderUpsertOne {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentOrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentOrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentOrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PaymentOrderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PaymentOrderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PaymentOrderCreateBulk is the builder for creating many PaymentOrder entities in bulk.
type PaymentOrderCreateBulk struct {
	config
	err      error
	builders []*PaymentOrderCreate
	conflict []sql.ConflictOption
}

// Save creates the PaymentOrder entities in the database.
func (_c *PaymentOrderCreateBulk) Save(ctx context.Context) ([]*PaymentOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentOrderCreateBulk) SaveX(ctx context.Context) []*PaymentOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PaymentOrder.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PaymentOrderUpsert) {
//			SetOrderNo(v+v).
//		}).
//		Exec(ctx)
func (_c *PaymentOrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *PaymentOrderUpsertBulk {
	_c.conflict = opts
	return &PaymentOrderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PaymentOrderCreateBulk) OnConflictColumns(columns ...string) *PaymentOrderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PaymentOrderUpsertBulk{
		create: _c,
	}
}

// PaymentOrderUpsertBulk is the builder for "upsert"-ing
// a bulk of PaymentOrder nodes.
type PaymentOrderUpsertBulk struct {
	create *PaymentOrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PaymentOrderUpsertBulk) UpdateNewValues() *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(paymentorder.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PaymentOrder.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PaymentOrderUpsertBulk) Ignore() *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PaymentOrderUpsertBulk) DoNothing() *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PaymentOrderCreateBulk.OnConflict
// documentation for more info.
func (u *PaymentOrderUpsertBulk) Update(set func(*PaymentOrderUpsert)) *PaymentOrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PaymentOrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *PaymentOrderUpsertBulk) SetOrderNo(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateOrderNo() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetUserID sets the "user_id" field.
func (u *PaymentOrderUpsertBulk) SetUserID(v int64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateUserID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUserID()
	})
}

// SetType sets the "type" field.
func (u *PaymentOrderUpsertBulk) SetType(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateType() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateType()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *PaymentOrderUpsertBulk) SetPlanID(v int64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdatePlanID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePlanID()
	})
}

// ClearPlanID clears the value of the "plan_id" field.
func (u *PaymentOrderUpsertBulk) ClearPlanID() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearPlanID()
	})
}

// SetAmount sets the "amount" field.
func (u *PaymentOrderUpsertBulk) SetAmount(v float64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *PaymentOrderUpsertBulk) AddAmount(v float64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateAmount() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAmount()
	})
}

// SetCreditAmount sets the "credit_amount" field.
func (u *PaymentOrderUpsertBulk) SetCreditAmount(v float64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetCreditAmount(v)
	})
}

// AddCreditAmount adds v to the "credit_amount" field.
func (u *PaymentOrderUpsertBulk) AddCreditAmount(v float64) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.AddCreditAmount(v)
	})
}

// UpdateCreditAmount sets the "credit_amount" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateCreditAmount() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateCreditAmount()
	})
}

// ClearCreditAmount clears the value of the "credit_amount" field.
func (u *PaymentOrderUpsertBulk) ClearCreditAmount() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearCreditAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *PaymentOrderUpsertBulk) SetCurrency(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateCurrency() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateCurrency()
	})
}

// SetStatus sets the "status" field.
func (u *PaymentOrderUpsertBulk) SetStatus(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateStatus() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateStatus()
	})
}

// SetProvider sets the "provider" field.
func (u *PaymentOrderUpsertBulk) SetProvider(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateProvider() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProvider()
	})
}

// ClearProvider clears the value of the "provider" field.
func (u *PaymentOrderUpsertBulk) ClearProvider() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearProvider()
	})
}

// SetProviderOrderNo sets the "provider_order_no" field.
func (u *PaymentOrderUpsertBulk) SetProviderOrderNo(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetProviderOrderNo(v)
	})
}

// UpdateProviderOrderNo sets the "provider_order_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateProviderOrderNo() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateProviderOrderNo()
	})
}

// ClearProviderOrderNo clears the value of the "provider_order_no" field.
func (u *PaymentOrderUpsertBulk) ClearProviderOrderNo() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearProviderOrderNo()
	})
}

// SetPaidAt sets the "paid_at" field.
func (u *PaymentOrderUpsertBulk) SetPaidAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetPaidAt(v)
	})
}

// UpdatePaidAt sets the "paid_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdatePaidAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdatePaidAt()
	})
}

// ClearPaidAt clears the value of the "paid_at" field.
func (u *PaymentOrderUpsertBulk) ClearPaidAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearPaidAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *PaymentOrderUpsertBulk) SetCompletedAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateCompletedAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *PaymentOrderUpsertBulk) ClearCompletedAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearCompletedAt()
	})
}

// SetRefundedAt sets the "refunded_at" field.
func (u *PaymentOrderUpsertBulk) SetRefundedAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetRefundedAt(v)
	})
}

// UpdateRefundedAt sets the "refunded_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateRefundedAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateRefundedAt()
	})
}

// ClearRefundedAt clears the value of the "refunded_at" field.
func (u *PaymentOrderUpsertBulk) ClearRefundedAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearRefundedAt()
	})
}

// SetExpiredAt sets the "expired_at" field.
func (u *PaymentOrderUpsertBulk) SetExpiredAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetExpiredAt(v)
	})
}

// UpdateExpiredAt sets the "expired_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateExpiredAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateExpiredAt()
	})
}

// SetCallbackRaw sets the "callback_raw" field.
func (u *PaymentOrderUpsertBulk) SetCallbackRaw(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetCallbackRaw(v)
	})
}

// UpdateCallbackRaw sets the "callback_raw" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateCallbackRaw() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateCallbackRaw()
	})
}

// ClearCallbackRaw clears the value of the "callback_raw" field.
func (u *PaymentOrderUpsertBulk) ClearCallbackRaw() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearCallbackRaw()
	})
}

// SetAdminNote sets the "admin_note" field.
func (u *PaymentOrderUpsertBulk) SetAdminNote(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetAdminNote(v)
	})
}

// UpdateAdminNote sets the "admin_note" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateAdminNote() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateAdminNote()
	})
}

// ClearAdminNote clears the value of the "admin_note" field.
func (u *PaymentOrderUpsertBulk) ClearAdminNote() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearAdminNote()
	})
}

// SetRefundNo sets the "refund_no" field.
func (u *PaymentOrderUpsertBulk) SetRefundNo(v string) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetRefundNo(v)
	})
}

// UpdateRefundNo sets the "refund_no" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateRefundNo() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateRefundNo()
	})
}

// ClearRefundNo clears the value of the "refund_no" field.
func (u *PaymentOrderUpsertBulk) ClearRefundNo() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.ClearRefundNo()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PaymentOrderUpsertBulk) SetUpdatedAt(v time.Time) *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PaymentOrderUpsertBulk) UpdateUpdatedAt() *PaymentOrderUpsertBulk {
	return u.Update(func(s *PaymentOrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *PaymentOrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PaymentOrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PaymentOrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PaymentOrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
