// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userreferral"
)

// UserReferralCreate is the builder for creating a UserReferral entity.
type UserReferralCreate struct {
	config
	mutation *UserReferralMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInviterID sets the "inviter_id" field.
func (_c *UserReferralCreate) SetInviterID(v int64) *UserReferralCreate {
	_c.mutation.SetInviterID(v)
	return _c
}

// SetInviteeID sets the "invitee_id" field.
func (_c *UserReferralCreate) SetInviteeID(v int64) *UserReferralCreate {
	_c.mutation.SetInviteeID(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *UserReferralCreate) SetCode(v string) *UserReferralCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetInviterRewarded sets the "inviter_rewarded" field.
func (_c *UserReferralCreate) SetInviterRewarded(v float64) *UserReferralCreate {
	_c.mutation.SetInviterRewarded(v)
	return _c
}

// SetNillableInviterRewarded sets the "inviter_rewarded" field if the given value is not nil.
func (_c *UserReferralCreate) SetNillableInviterRewarded(v *float64) *UserReferralCreate {
	if v != nil {
		_c.SetInviterRewarded(*v)
	}
	return _c
}

// SetInviteeRewarded sets the "invitee_rewarded" field.
func (_c *UserReferralCreate) SetInviteeRewarded(v float64) *UserReferralCreate {
	_c.mutation.SetInviteeRewarded(v)
	return _c
}

// SetNillableInviteeRewarded sets the "invitee_rewarded" field if the given value is not nil.
func (_c *UserReferralCreate) SetNillableInviteeRewarded(v *float64) *UserReferralCreate {
	if v != nil {
		_c.SetInviteeRewarded(*v)
	}
	return _c
}

// SetInviterRewardSnapshot sets the "inviter_reward_snapshot" field.
func (_c *UserReferralCreate) SetInviterRewardSnapshot(v float64) *UserReferralCreate {
	_c.mutation.SetInviterRewardSnapshot(v)
	return _c
}

// SetNillableInviterRewardSnapshot sets the "inviter_reward_snapshot" field if the given value is not nil.
func (_c *UserReferralCreate) SetNillableInviterRewardSnapshot(v *float64) *UserReferralCreate {
	if v != nil {
		_c.SetInviterRewardSnapshot(*v)
	}
	return _c
}

// SetInviteeRewardSnapshot sets the "invitee_reward_snapshot" field.
func (_c *UserReferralCreate) SetInviteeRewardSnapshot(v float64) *UserReferralCreate {
	_c.mutation.SetInviteeRewardSnapshot(v)
	return _c
}

// SetNillableInviteeRewardSnapshot sets the "invitee_reward_snapshot" field if the given value is not nil.
func (_c *UserReferralCreate) SetNillableInviteeRewardSnapshot(v *float64) *UserReferralCreate {
	if v != nil {
		_c.SetInviteeRewardSnapshot(*v)
	}
	return _c
}

// SetRewardGrantedAt sets the "reward_granted_at" field.
func (_c *UserReferralCreate) SetRewardGrantedAt(v time.Time) *UserReferralCreate {
	_c.mutation.SetRewardGrantedAt(v)
	return _c
}

// SetNillableRewardGrantedAt sets the "reward_granted_at" field if the given value is not nil.
func (_c *UserReferralCreate) SetNillableRewardGrantedAt(v *time.Time) *UserReferralCreate {
	if v != nil {
		_c.SetRewardGrantedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserReferralCreate) SetCreatedAt(v time.Time) *UserReferralCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserReferralCreate) SetNillableCreatedAt(v *time.Time) *UserReferralCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetInviter sets the "inviter" edge to the User entity.
func (_c *UserReferralCreate) SetInviter(v *User) *UserReferralCreate {
	return _c.SetInviterID(v.ID)
}

// SetInvitee sets the "invitee" edge to the User entity.
func (_c *UserReferralCreate) SetInvitee(v *User) *UserReferralCreate {
	return _c.SetInviteeID(v.ID)
}

// Mutation returns the UserReferralMutation object of the builder.
func (_c *UserReferralCreate) Mutation() *UserReferralMutation {
	return _c.mutation
}

// Save creates the UserReferral in the database.
func (_c *UserReferralCreate) Save(ctx context.Context) (*UserReferral, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserReferralCreate) SaveX(ctx context.Context) *UserReferral {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserReferralCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserReferralCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserReferralCreate) defaults() {
	if _, ok := _c.mutation.InviterRewarded(); !ok {
		v := userreferral.DefaultInviterRewarded
		_c.mutation.SetInviterRewarded(v)
	}
	if _, ok := _c.mutation.InviteeRewarded(); !ok {
		v := userreferral.DefaultInviteeRewarded
		_c.mutation.SetInviteeRewarded(v)
	}
	if _, ok := _c.mutation.InviterRewardSnapshot(); !ok {
		v := userreferral.DefaultInviterRewardSnapshot
		_c.mutation.SetInviterRewardSnapshot(v)
	}
	if _, ok := _c.mutation.InviteeRewardSnapshot(); !ok {
		v := userreferral.DefaultInviteeRewardSnapshot
		_c.mutation.SetInviteeRewardSnapshot(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userreferral.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserReferralCreate) check() error {
	if _, ok := _c.mutation.InviterID(); !ok {
		return &ValidationError{Name: "inviter_id", err: errors.New(`ent: missing required field "UserReferral.inviter_id"`)}
	}
	if _, ok := _c.mutation.InviteeID(); !ok {
		return &ValidationError{Name: "invitee_id", err: errors.New(`ent: missing required field "UserReferral.invitee_id"`)}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "UserReferral.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := userreferral.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "UserReferral.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.InviterRewarded(); !ok {
		return &ValidationError{Name: "inviter_rewarded", err: errors.New(`ent: missing required field "UserReferral.inviter_rewarded"`)}
	}
	if _, ok := _c.mutation.InviteeRewarded(); !ok {
		return &ValidationError{Name: "invitee_rewarded", err: errors.New(`ent: missing required field "UserReferral.invitee_rewarded"`)}
	}
	if _, ok := _c.mutation.InviterRewardSnapshot(); !ok {
		return &ValidationError{Name: "inviter_reward_snapshot", err: errors.New(`ent: missing required field "UserReferral.inviter_reward_snapshot"`)}
	}
	if _, ok := _c.mutation.InviteeRewardSnapshot(); !ok {
		return &ValidationError{Name: "invitee_reward_snapshot", err: errors.New(`ent: missing required field "UserReferral.invitee_reward_snapshot"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserReferral.created_at"`)}
	}
	if len(_c.mutation.InviterIDs()) == 0 {
		return &ValidationError{Name: "inviter", err: errors.New(`ent: missing required edge "UserReferral.inviter"`)}
	}
	if len(_c.mutation.InviteeIDs()) == 0 {
		return &ValidationError{Name: "invitee", err: errors.New(`ent: missing required edge "UserReferral.invitee"`)}
	}
	return nil
}

func (_c *UserReferralCreate) sqlSave(ctx context.Context) (*UserReferral, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserReferralCreate) createSpec() (*UserReferral, *sqlgraph.CreateSpec) {
	var (
		_node = &UserReferral{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userreferral.Table, sqlgraph.NewFieldSpec(userreferral.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(userreferral.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.InviterRewarded(); ok {
		_spec.SetField(userreferral.FieldInviterRewarded, field.TypeFloat64, value)
		_node.InviterRewarded = value
	}
	if value, ok := _c.mutation.InviteeRewarded(); ok {
		_spec.SetField(userreferral.FieldInviteeRewarded, field.TypeFloat64, value)
		_node.InviteeRewarded = value
	}
	if value, ok := _c.mutation.InviterRewardSnapshot(); ok {
		_spec.SetField(userreferral.FieldInviterRewardSnapshot, field.TypeFloat64, value)
		_node.InviterRewardSnapshot = value
	}
	if value, ok := _c.mutation.InviteeRewardSnapshot(); ok {
		_spec.SetField(userreferral.FieldInviteeRewardSnapshot, field.TypeFloat64, value)
		_node.InviteeRewardSnapshot = value
	}
	if value, ok := _c.mutation.RewardGrantedAt(); ok {
		_spec.SetField(userreferral.FieldRewardGrantedAt, field.TypeTime, value)
		_node.RewardGrantedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userreferral.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.InviterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userreferral.InviterTable,
			Columns: []string{userreferral.InviterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InviterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InviteeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userreferral.InviteeTable,
			Columns: []string{userreferral.InviteeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InviteeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserReferral.Create().
//		SetInviterID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserReferralUpsert) {
//			SetInviterID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserReferralCreate) OnConflict(opts ...sql.ConflictOption) *UserReferralUpsertOne {
	_c.conflict = opts
	return &UserReferralUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserReferral.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserReferralCreate) OnConflictColumns(columns ...string) *UserReferralUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserReferralUpsertOne{
		create: _c,
	}
}

type (
	// UserReferralUpsertOne is the builder for "upsert"-ing
	//  one UserReferral node.
	UserReferralUpsertOne struct {
		create *UserReferralCreate
	}

	// UserReferralUpsert is the "OnConflict" setter.
	UserReferralUpsert struct {
		*sql.UpdateSet
	}
)

// SetInviterID sets the "inviter_id" field.
func (u *UserReferralUpsert) SetInviterID(v int64) *UserReferralUpsert {
	u.Set(userreferral.FieldInviterID, v)
	return u
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *UserReferralUpsert) UpdateInviterID() *UserReferralUpsert {
	u.SetExcluded(userreferral.FieldInviterID)
	return u
}

// SetInviteeID sets the "invitee_id" field.
func (u *UserReferralUpsert) SetInviteeID(v int64) *UserReferralUpsert {
	u.Set(userreferral.FieldInviteeID, v)
	return u
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *UserReferralUpsert) UpdateInviteeID() *UserReferralUpsert {
	u.SetExcluded(userreferral.FieldInviteeID)
	return u
}

// SetCode sets the "code" field.
func (u *UserReferralUpsert) SetCode(v string) *UserReferralUpsert {
	u.Set(userreferral.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *UserReferralUpsert) UpdateCode() *UserReferralUpsert {
	u.SetExcluded(userreferral.FieldCode)
	return u
}

// SetInviterRewarded sets the "inviter_rewarded" field.
func (u *UserReferralUpsert) SetInviterRewarded(v float64) *UserReferralUpsert {
	u.Set(userreferral.FieldInviterRewarded, v)
	return u
}

// UpdateInviterRewarded sets the "inviter_rewarded" field to the value that was provided on create.
func (u *UserReferralUpsert) UpdateInviterRewarded() *UserReferralUpsert {
	u.SetExcluded(userreferral.FieldInviterRewarded)
	return u
}

// AddInviterRewarded adds v to the "inviter_rewarded" field.
func (u *UserReferralUpsert) AddInviterRewarded(v float64) *UserReferralUpsert {
	u.Add(userreferral.FieldInviterRewarded, v)
	return u
}

// SetInviteeRewarded sets the "invitee_rewarded" field.
func (u *UserReferralUpsert) SetInviteeRewarded(v float64) *UserReferralUpsert {
	u.Set(userreferral.FieldInviteeRewarded, v)
	return u
}

// UpdateInviteeRewarded sets the "invitee_rewarded" field to the value that was provided on create.
func (u *UserReferralUpsert) UpdateInviteeRewarded() *UserReferralUpsert {
	u.SetExcluded(userreferral.FieldInviteeRewarded)
	return u
}

// AddInviteeRewarded adds v to the "invitee_rewarded" field.
func (u *UserReferralUpsert) AddInviteeRewarded(v float64) *UserReferralUpsert {
	u.Add(userreferral.FieldInviteeRewarded, v)
	return u
}

// SetInviterRewardSnapshot sets the "inviter_reward_snapshot" field.
func (u *UserReferralUpsert) SetInviterRewardSnapshot(v float64) *UserReferralUpsert {
	u.Set(userreferral.FieldInviterRewardSnapshot, v)
	return u
}

// UpdateInviterRewardSnapshot sets the "inviter_reward_snapshot" field to the value that was provided on create.
func (u *UserReferralUpsert) UpdateInviterRewardSnapshot() *UserReferralUpsert {
	u.SetExcluded(userreferral.FieldInviterRewardSnapshot)
	return u
}

// AddInviterRewardSnapshot adds v to the "inviter_reward_snapshot" field.
func (u *UserReferralUpsert) AddInviterRewardSnapshot(v float64) *UserReferralUpsert {
	u.Add(userreferral.FieldInviterRewardSnapshot, v)
	return u
}

// SetInviteeRewardSnapshot sets the "invitee_reward_snapshot" field.
func (u *UserReferralUpsert) SetInviteeRewardSnapshot(v float64) *UserReferralUpsert {
	u.Set(userreferral.FieldInviteeRewardSnapshot, v)
	return u
}

// UpdateInviteeRewardSnapshot sets the "invitee_reward_snapshot" field to the value that was provided on create.
func (u *UserReferralUpsert) UpdateInviteeRewardSnapshot() *UserReferralUpsert {
	u.SetExcluded(userreferral.FieldInviteeRewardSnapshot)
	return u
}

// AddInviteeRewardSnapshot adds v to the "invitee_reward_snapshot" field.
func (u *UserReferralUpsert) AddInviteeRewardSnapshot(v float64) *UserReferralUpsert {
	u.Add(userreferral.FieldInviteeRewardSnapshot, v)
	return u
}

// SetRewardGrantedAt sets the "reward_granted_at" field.
func (u *UserReferralUpsert) SetRewardGrantedAt(v time.Time) *UserReferralUpsert {
	u.Set(userreferral.FieldRewardGrantedAt, v)
	return u
}

// UpdateRewardGrantedAt sets the "reward_granted_at" field to the value that was provided on create.
func (u *UserReferralUpsert) UpdateRewardGrantedAt() *UserReferralUpsert {
	u.SetExcluded(userreferral.FieldRewardGrantedAt)
	return u
}

// ClearRewardGrantedAt clears the value of the "reward_granted_at" field.
func (u *UserReferralUpsert) ClearRewardGrantedAt() *UserReferralUpsert {
	u.SetNull(userreferral.FieldRewardGrantedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UserReferral.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserReferralUpsertOne) UpdateNewValues() *UserReferralUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(userreferral.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserReferral.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UserReferralUpsertOne) Ignore() *UserReferralUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserReferralUpsertOne) DoNothing() *UserReferralUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserReferralCreate.OnConflict
// documentation for more info.
func (u *UserReferralUpsertOne) Update(set func(*UserReferralUpsert)) *UserReferralUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserReferralUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviterID sets the "inviter_id" field.
func (u *UserReferralUpsertOne) SetInviterID(v int64) *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.SetInviterID(v)
	})
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *UserReferralUpsertOne) UpdateInviterID() *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.UpdateInviterID()
	})
}

// SetInviteeID sets the "invitee_id" field.
func (u *UserReferralUpsertOne) SetInviteeID(v int64) *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.SetInviteeID(v)
	})
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *UserReferralUpsertOne) UpdateInviteeID() *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.UpdateInviteeID()
	})
}

// SetCode sets the "code" field.
func (u *UserReferralUpsertOne) SetCode(v string) *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *UserReferralUpsertOne) UpdateCode() *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.UpdateCode()
	})
}

// SetInviterRewarded sets the "inviter_rewarded" field.
func (u *UserReferralUpsertOne) SetInviterRewarded(v float64) *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.SetInviterRewarded(v)
	})
}

// AddInviterRewarded adds v to the "inviter_rewarded" field.
func (u *UserReferralUpsertOne) AddInviterRewarded(v float64) *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.AddInviterRewarded(v)
	})
}

// UpdateInviterRewarded sets the "inviter_rewarded" field to the value that was provided on create.
func (u *UserReferralUpsertOne) UpdateInviterRewarded() *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.UpdateInviterRewarded()
	})
}

// SetInviteeRewarded sets the "invitee_rewarded" field.
func (u *UserReferralUpsertOne) SetInviteeRewarded(v float64) *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.SetInviteeRewarded(v)
	})
}

// AddInviteeRewarded adds v to the "invitee_rewarded" field.
func (u *UserReferralUpsertOne) AddInviteeRewarded(v float64) *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.AddInviteeRewarded(v)
	})
}

// UpdateInviteeRewarded sets the "invitee_rewarded" field to the value that was provided on create.
func (u *UserReferralUpsertOne) UpdateInviteeRewarded() *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.UpdateInviteeRewarded()
	})
}

// SetInviterRewardSnapshot sets the "inviter_reward_snapshot" field.
func (u *UserReferralUpsertOne) SetInviterRewardSnapshot(v float64) *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.SetInviterRewardSnapshot(v)
	})
}

// AddInviterRewardSnapshot adds v to the "inviter_reward_snapshot" field.
func (u *UserReferralUpsertOne) AddInviterRewardSnapshot(v float64) *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.AddInviterRewardSnapshot(v)
	})
}

// UpdateInviterRewardSnapshot sets the "inviter_reward_snapshot" field to the value that was provided on create.
func (u *UserReferralUpsertOne) UpdateInviterRewardSnapshot() *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.UpdateInviterRewardSnapshot()
	})
}

// SetInviteeRewardSnapshot sets the "invitee_reward_snapshot" field.
func (u *UserReferralUpsertOne) SetInviteeRewardSnapshot(v float64) *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.SetInviteeRewardSnapshot(v)
	})
}

// AddInviteeRewardSnapshot adds v to the "invitee_reward_snapshot" field.
func (u *UserReferralUpsertOne) AddInviteeRewardSnapshot(v float64) *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.AddInviteeRewardSnapshot(v)
	})
}

// UpdateInviteeRewardSnapshot sets the "invitee_reward_snapshot" field to the value that was provided on create.
func (u *UserReferralUpsertOne) UpdateInviteeRewardSnapshot() *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.UpdateInviteeRewardSnapshot()
	})
}

// SetRewardGrantedAt sets the "reward_granted_at" field.
func (u *UserReferralUpsertOne) SetRewardGrantedAt(v time.Time) *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.SetRewardGrantedAt(v)
	})
}

// UpdateRewardGrantedAt sets the "reward_granted_at" field to the value that was provided on create.
func (u *UserReferralUpsertOne) UpdateRewardGrantedAt() *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.UpdateRewardGrantedAt()
	})
}

// ClearRewardGrantedAt clears the value of the "reward_granted_at" field.
func (u *UserReferralUpsertOne) ClearRewardGrantedAt() *UserReferralUpsertOne {
	return u.Update(func(s *UserReferralUpsert) {
		s.ClearRewardGrantedAt()
	})
}

// Exec executes the query.
func (u *UserReferralUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserReferralCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserReferralUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UserReferralUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UserReferralUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UserReferralCreateBulk is the builder for creating many UserReferral entities in bulk.
type UserReferralCreateBulk struct {
	config
	err      error
	builders []*UserReferralCreate
	conflict []sql.ConflictOption
}

// Save creates the UserReferral entities in the database.
func (_c *UserReferralCreateBulk) Save(ctx context.Context) ([]*UserReferral, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserReferral, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserReferralMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserReferralCreateBulk) SaveX(ctx context.Context) []*UserReferral {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserReferralCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserReferralCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UserReferral.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserReferralUpsert) {
//			SetInviterID(v+v).
//		}).
//		Exec(ctx)
func (_c *UserReferralCreateBulk) OnConflict(opts ...sql.ConflictOption) *UserReferralUpsertBulk {
	_c.conflict = opts
	return &UserReferralUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UserReferral.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UserReferralCreateBulk) OnConflictColumns(columns ...string) *UserReferralUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UserReferralUpsertBulk{
		create: _c,
	}
}

// UserReferralUpsertBulk is the builder for "upsert"-ing
// a bulk of UserReferral nodes.
type UserReferralUpsertBulk struct {
	create *UserReferralCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UserReferral.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UserReferralUpsertBulk) UpdateNewValues() *UserReferralUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(userreferral.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UserReferral.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UserReferralUpsertBulk) Ignore() *UserReferralUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UserReferralUpsertBulk) DoNothing() *UserReferralUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UserReferralCreateBulk.OnConflict
// documentation for more info.
func (u *UserReferralUpsertBulk) Update(set func(*UserReferralUpsert)) *UserReferralUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UserReferralUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviterID sets the "inviter_id" field.
func (u *UserReferralUpsertBulk) SetInviterID(v int64) *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.SetInviterID(v)
	})
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *UserReferralUpsertBulk) UpdateInviterID() *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.UpdateInviterID()
	})
}

// SetInviteeID sets the "invitee_id" field.
func (u *UserReferralUpsertBulk) SetInviteeID(v int64) *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.SetInviteeID(v)
	})
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *UserReferralUpsertBulk) UpdateInviteeID() *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.UpdateInviteeID()
	})
}

// SetCode sets the "code" field.
func (u *UserReferralUpsertBulk) SetCode(v string) *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *UserReferralUpsertBulk) UpdateCode() *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.UpdateCode()
	})
}

// SetInviterRewarded sets the "inviter_rewarded" field.
func (u *UserReferralUpsertBulk) SetInviterRewarded(v float64) *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.SetInviterRewarded(v)
	})
}

// AddInviterRewarded adds v to the "inviter_rewarded" field.
func (u *UserReferralUpsertBulk) AddInviterRewarded(v float64) *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.AddInviterRewarded(v)
	})
}

// UpdateInviterRewarded sets the "inviter_rewarded" field to the value that was provided on create.
func (u *UserReferralUpsertBulk) UpdateInviterRewarded() *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.UpdateInviterRewarded()
	})
}

// SetInviteeRewarded sets the "invitee_rewarded" field.
func (u *UserReferralUpsertBulk) SetInviteeRewarded(v float64) *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.SetInviteeRewarded(v)
	})
}

// AddInviteeRewarded adds v to the "invitee_rewarded" field.
func (u *UserReferralUpsertBulk) AddInviteeRewarded(v float64) *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.AddInviteeRewarded(v)
	})
}

// UpdateInviteeRewarded sets the "invitee_rewarded" field to the value that was provided on create.
func (u *UserReferralUpsertBulk) UpdateInviteeRewarded() *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.UpdateInviteeRewarded()
	})
}

// SetInviterRewardSnapshot sets the "inviter_reward_snapshot" field.
func (u *UserReferralUpsertBulk) SetInviterRewardSnapshot(v float64) *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.SetInviterRewardSnapshot(v)
	})
}

// AddInviterRewardSnapshot adds v to the "inviter_reward_snapshot" field.
func (u *UserReferralUpsertBulk) AddInviterRewardSnapshot(v float64) *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.AddInviterRewardSnapshot(v)
	})
}

// UpdateInviterRewardSnapshot sets the "inviter_reward_snapshot" field to the value that was provided on create.
func (u *UserReferralUpsertBulk) UpdateInviterRewardSnapshot() *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.UpdateInviterRewardSnapshot()
	})
}

// SetInviteeRewardSnapshot sets the "invitee_reward_snapshot" field.
func (u *UserReferralUpsertBulk) SetInviteeRewardSnapshot(v float64) *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.SetInviteeRewardSnapshot(v)
	})
}

// AddInviteeRewardSnapshot adds v to the "invitee_reward_snapshot" field.
func (u *UserReferralUpsertBulk) AddInviteeRewardSnapshot(v float64) *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.AddInviteeRewardSnapshot(v)
	})
}

// UpdateInviteeRewardSnapshot sets the "invitee_reward_snapshot" field to the value that was provided on create.
func (u *UserReferralUpsertBulk) UpdateInviteeRewardSnapshot() *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.UpdateInviteeRewardSnapshot()
	})
}

// SetRewardGrantedAt sets the "reward_granted_at" field.
func (u *UserReferralUpsertBulk) SetRewardGrantedAt(v time.Time) *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.SetRewardGrantedAt(v)
	})
}

// UpdateRewardGrantedAt sets the "reward_granted_at" field to the value that was provided on create.
func (u *UserReferralUpsertBulk) UpdateRewardGrantedAt() *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.UpdateRewardGrantedAt()
	})
}

// ClearRewardGrantedAt clears the value of the "reward_granted_at" field.
func (u *UserReferralUpsertBulk) ClearRewardGrantedAt() *UserReferralUpsertBulk {
	return u.Update(func(s *UserReferralUpsert) {
		s.ClearRewardGrantedAt()
	})
}

// Exec executes the query.
func (u *UserReferralUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UserReferralCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UserReferralCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UserReferralUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
