// Code generated by ent, DO NOT EDIT.

package imagecreationtemplate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the imagecreationtemplate type in the database.
	Label = "image_creation_template"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldState holds the string denoting the state field in the database.
	FieldState = "state"
	// FieldDraftData holds the string denoting the draft_data field in the database.
	FieldDraftData = "draft_data"
	// FieldPublishedData holds the string denoting the published_data field in the database.
	FieldPublishedData = "published_data"
	// FieldRevision holds the string denoting the revision field in the database.
	FieldRevision = "revision"
	// FieldPublishedVersion holds the string denoting the published_version field in the database.
	FieldPublishedVersion = "published_version"
	// FieldDraftCoverAssetID holds the string denoting the draft_cover_asset_id field in the database.
	FieldDraftCoverAssetID = "draft_cover_asset_id"
	// FieldPublishedCoverAssetID holds the string denoting the published_cover_asset_id field in the database.
	FieldPublishedCoverAssetID = "published_cover_asset_id"
	// FieldHomePosition holds the string denoting the home_position field in the database.
	FieldHomePosition = "home_position"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// EdgeDraftCover holds the string denoting the draft_cover edge name in mutations.
	EdgeDraftCover = "draft_cover"
	// EdgePublishedCover holds the string denoting the published_cover edge name in mutations.
	EdgePublishedCover = "published_cover"
	// EdgeCreator holds the string denoting the creator edge name in mutations.
	EdgeCreator = "creator"
	// EdgeUpdater holds the string denoting the updater edge name in mutations.
	EdgeUpdater = "updater"
	// Table holds the table name of the imagecreationtemplate in the database.
	Table = "image_creation_templates"
	// DraftCoverTable is the table that holds the draft_cover relation/edge.
	DraftCoverTable = "image_creation_templates"
	// DraftCoverInverseTable is the table name for the ImageCreationAsset entity.
	// It exists in this package in order to avoid circular dependency with the "imagecreationasset" package.
	DraftCoverInverseTable = "image_creation_assets"
	// DraftCoverColumn is the table column denoting the draft_cover relation/edge.
	DraftCoverColumn = "draft_cover_asset_id"
	// PublishedCoverTable is the table that holds the published_cover relation/edge.
	PublishedCoverTable = "image_creation_templates"
	// PublishedCoverInverseTable is the table name for the ImageCreationAsset entity.
	// It exists in this package in order to avoid circular dependency with the "imagecreationasset" package.
	PublishedCoverInverseTable = "image_creation_assets"
	// PublishedCoverColumn is the table column denoting the published_cover relation/edge.
	PublishedCoverColumn = "published_cover_asset_id"
	// CreatorTable is the table that holds the creator relation/edge.
	CreatorTable = "image_creation_templates"
	// CreatorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreatorInverseTable = "users"
	// CreatorColumn is the table column denoting the creator relation/edge.
	CreatorColumn = "created_by"
	// UpdaterTable is the table that holds the updater relation/edge.
	UpdaterTable = "image_creation_templates"
	// UpdaterInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UpdaterInverseTable = "users"
	// UpdaterColumn is the table column denoting the updater relation/edge.
	UpdaterColumn = "updated_by"
)

// Columns holds all SQL columns for imagecreationtemplate fields.
var Columns = []string{
	FieldID,
	FieldState,
	FieldDraftData,
	FieldPublishedData,
	FieldRevision,
	FieldPublishedVersion,
	FieldDraftCoverAssetID,
	FieldPublishedCoverAssetID,
	FieldHomePosition,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPublishedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultState holds the default value on creation for the "state" field.
	DefaultState string
	// StateValidator is a validator for the "state" field. It is called by the builders before save.
	StateValidator func(string) error
	// DefaultRevision holds the default value on creation for the "revision" field.
	DefaultRevision int
	// RevisionValidator is a validator for the "revision" field. It is called by the builders before save.
	RevisionValidator func(int) error
	// DefaultPublishedVersion holds the default value on creation for the "published_version" field.
	DefaultPublishedVersion int
	// PublishedVersionValidator is a validator for the "published_version" field. It is called by the builders before save.
	PublishedVersionValidator func(int) error
	// DraftCoverAssetIDValidator is a validator for the "draft_cover_asset_id" field. It is called by the builders before save.
	DraftCoverAssetIDValidator func(string) error
	// PublishedCoverAssetIDValidator is a validator for the "published_cover_asset_id" field. It is called by the builders before save.
	PublishedCoverAssetIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ImageCreationTemplate queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByState orders the results by the state field.
func ByState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldState, opts...).ToFunc()
}

// ByRevision orders the results by the revision field.
func ByRevision(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRevision, opts...).ToFunc()
}

// ByPublishedVersion orders the results by the published_version field.
func ByPublishedVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedVersion, opts...).ToFunc()
}

// ByDraftCoverAssetID orders the results by the draft_cover_asset_id field.
func ByDraftCoverAssetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDraftCoverAssetID, opts...).ToFunc()
}

// ByPublishedCoverAssetID orders the results by the published_cover_asset_id field.
func ByPublishedCoverAssetID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedCoverAssetID, opts...).ToFunc()
}

// ByHomePosition orders the results by the home_position field.
func ByHomePosition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHomePosition, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByDraftCoverField orders the results by draft_cover field.
func ByDraftCoverField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDraftCoverStep(), sql.OrderByField(field, opts...))
	}
}

// ByPublishedCoverField orders the results by published_cover field.
func ByPublishedCoverField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPublishedCoverStep(), sql.OrderByField(field, opts...))
	}
}

// ByCreatorField orders the results by creator field.
func ByCreatorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatorStep(), sql.OrderByField(field, opts...))
	}
}

// ByUpdaterField orders the results by updater field.
func ByUpdaterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUpdaterStep(), sql.OrderByField(field, opts...))
	}
}
func newDraftCoverStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DraftCoverInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, DraftCoverTable, DraftCoverColumn),
	)
}
func newPublishedCoverStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PublishedCoverInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PublishedCoverTable, PublishedCoverColumn),
	)
}
func newCreatorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
	)
}
func newUpdaterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UpdaterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UpdaterTable, UpdaterColumn),
	)
}
